import { MetadataRoute } from 'next';
import { SITE, CATEGORIES, PRODUCTS, POSTS } from '@/config/site';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = `https://${SITE.domain}`;
  // Date-only (YYYY-MM-DD) is valid W3C datetime and avoids stamping every URL
  // with an identical build-time millisecond, which reads as machine noise.
  const now = new Date().toISOString().slice(0, 10);

  const coreRoutes: MetadataRoute.Sitemap = [
    {
      url: `${baseUrl}/`,
      lastModified: now,
      changeFrequency: 'daily',
      priority: 1.0,
    },
    {
      url: `${baseUrl}/shop/`,
      lastModified: now,
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/compare/`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/finance/`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/about/`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog/`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/faq/`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/wholesale/`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/contact/`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    // /search/ is deliberately omitted — it is noindex (see app/search/layout.tsx).
  ];

  const categoryRoutes: MetadataRoute.Sitemap = CATEGORIES.map((c) => ({
    url: `${baseUrl}/shop/${c.slug}/`,
    lastModified: now,
    changeFrequency: 'weekly',
    priority: 0.85,
  }));

  // The brand hubs live canonically at /brands/<slug>/ (each page sets that
  // canonical) — list them so search engines index the canonical URL, not
  // just the /shop/<slug>/ view generated by the shared [category] route.
  const brandRoutes: MetadataRoute.Sitemap = CATEGORIES
    .filter((c) => c.section === 'brands' && c.parent === 'brands')
    .map((c) => ({
      url: `${baseUrl}/brands/${c.slug}/`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.8,
    }));

  const productRoutes: MetadataRoute.Sitemap = PRODUCTS.map((p) => ({
    url: `${baseUrl}/shop/${p.category}/${p.slug}/`,
    lastModified: now,
    changeFrequency: 'weekly',
    priority: 0.9,
  }));

  const blogRoutes: MetadataRoute.Sitemap = POSTS.map((post) => ({
    url: `${baseUrl}/blog/${post.slug}/`,
    lastModified: (post as { date?: string }).date || now,
    changeFrequency: 'monthly',
    priority: 0.75,
  }));

  return [...coreRoutes, ...categoryRoutes, ...brandRoutes, ...productRoutes, ...blogRoutes];
}
