// src/config/accessories.js
// Australian Market Product Catalog: Accessories & Maintenance
// High-grade pit equipment, transport gear, graphics & e-moto cleaning essentials
// Realistic AUD pricing (inc. GST)

export const ACCESSORIES_CATEGORIES = [
  {
    slug: 'bike-stands-tools',
    name: 'Bike Stands & Pit Mats',
    url: '/accessories/bike-stands-tools/',
    description: 'Foldable composite and aircraft-grade aluminum pit stands, heavy-duty lift stands, and FIM-approved environmental absorbent pit mats for electric dirt bikes.',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'storage-transport',
    name: 'Transport & Hitch Carriers',
    url: '/accessories/storage-transport/',
    description: 'Heavy-duty 2-inch hitch bike carriers, anti-scratch soft-loop tie-down straps, and 420D weatherproof heavy-duty outdoor covers designed for e-moto transport.',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'graphics-plastics-kits',
    name: 'Custom Graphics & Plastics Kits',
    url: '/accessories/graphics-plastics-kits/',
    description: 'Heavy-duty 21 mil ultra-thick vinyl custom graphic decals and durable gloss polypropylene restyle plastics for Surron, Talaria, E-Ride Pro and Stark VARG.',
    image: 'https://images.unsplash.com/photo-1547038577-da80abbc4f19?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'maintenance-chemicals',
    name: 'E-Moto Cleaning & Chain Lubes',
    url: '/accessories/maintenance-chemicals/',
    description: 'Waterless bike wash sprays, specialized O-ring/X-ring synthetic PTFE off-road chain lubricants, and waterless electrical contact cleaners safe for high-voltage e-dirt bikes.',
    image: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=1200&q=80',
  },
];

export const STARTER_PACK_BUNDLE = {
  id: 'starter-pack-bundle',
  slug: 'essential-starter-pack',
  name: 'Essential Starter Pack',
  tagline: 'Polisport Foldable Stand + Ballard’s Tie-Downs + Muc-Off Waterless Wash',
  originalPrice: 270,
  bundlePrice: 229,
  price: 229,
  savings: 41,
  savingsPercent: 15,
  discountPercent: 15,
  image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
  description: 'The must-have gear kit for every new electric dirt bike owner in Australia. Includes a space-saving 250kg rated foldable stand, heavy-duty soft-loop ratchet tie-downs for ute/trailer hauling, and electrical-safe waterless wash.',
  includedItems: [
    {
      name: 'Polisport Foldable Bike Stand',
      slug: 'polisport-foldable-bike-stand',
      individualPrice: 149,
      price: 149,
      image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=600&q=80',
    },
    {
      name: "Ballard's Ratchet Tie-Down Straps (Pair)",
      slug: 'ballards-ratchet-tie-down-straps',
      individualPrice: 49,
      price: 49,
      image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=600&q=80',
    },
    {
      name: 'Muc-Off High-Performance Waterless Wash (750ml)',
      slug: 'muc-off-waterless-wash-750ml',
      individualPrice: 29,
      price: 29,
      image: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=600&q=80',
    },
  ],
  items: [
    {
      name: 'Polisport Foldable Bike Stand',
      slug: 'polisport-foldable-bike-stand',
      price: 149,
    },
    {
      name: "Ballard's Ratchet Tie-Down Straps (Pair)",
      slug: 'ballards-ratchet-tie-down-straps',
      price: 49,
    },
    {
      name: 'Muc-Off High-Performance Waterless Wash (750ml)',
      slug: 'muc-off-waterless-wash-750ml',
      price: 29,
    },
  ],
};

export const ACCESSORIES_PRODUCTS = [
  // =========================================================================
  // SUB-CATEGORY 1: Bike Stands & Pit Mats
  // =========================================================================
  {
    slug: 'polisport-foldable-bike-stand',
    name: 'Polisport Foldable Pit Bike Stand',
    price: 149,
    category: 'bike-stands-tools',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'bike-stands-tools'],
    brand: 'polisport',
    brandName: 'Polisport',
    badge: 'Space-Saving 250kg',
    featured: true,
    isAccessory: true,
    images: [
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1547038577-da80abbc4f19?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: 'Patented folding design holds up to 250kg with reinforced bi-material polypropylene and non-slip rubber top pad.',
    description: 'The award-winning Polisport Foldable Bike Stand is the ideal pit accessory for electric dirt bike owners. Collapses flat in one second with an integrated carrying handle, making it easy to store in the back of your ute, SUV trunk, or garage. Constructed from high-strength reinforced bi-material polypropylene composite capable of supporting heavy bikes up to 250kg without flexing.',
    specs: {
      WeightCapacity: '250 kg (552 lbs) Static Weight Rating',
      FoldedThickness: 'Compact 50mm flat profile when closed',
      TopPad: 'Chemical-Resistant Molded Rubber Non-Slip Surface',
      Structure: 'Reinforced High-Impact Polypropylene & Rubber Compound',
      Transport: 'Integrated Built-in Dual Carrying Handle',
      Dimensions: 'Open: 43cm (H) x 42cm (W) x 40cm (D)',
      Weight: '3.7 kg',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'matrix-concepts-a2-aluminum-pit-stand',
    name: 'Matrix Concepts A2 Aluminum Pit Stand',
    price: 189,
    category: 'bike-stands-tools',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'bike-stands-tools'],
    brand: 'matrix-concepts',
    brandName: 'Matrix Concepts',
    badge: '6063 Aircraft Alloy',
    featured: false,
    isAccessory: true,
    images: [
      'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: 'TIG-welded 6063 aircraft-grade aluminum, anti-slip oil and chemical resistant top pad with 225kg capacity.',
    description: 'Engineered for pro pit crews and track days. Built from lightweight 1.25" 6063 aircraft-grade rectangular aluminum tubing with precision TIG welds. Features a replaceable extra-wide embossed top pad with oil, brake cleaner, and chemical resistance, plus a heavy-duty lower tool storage tray.',
    specs: {
      Material: '1.25-inch 6063 Aircraft Grade Aluminum Tubing',
      WeightCapacity: '225 kg (500 lbs)',
      Welding: 'Robotic Continuous High-Strength TIG Welds',
      TopPad: 'Removable Chemical Resistant Molded Rubber Top Plate with Center Drain Hole',
      Height: 'Standard 430mm (17 inches) Pit Height',
      Weight: '2.8 kg Ultra-Lightweight',
      Warranty: '2-Year Australian Warranty',
    },
  },
  {
    slug: 'factory-effex-environmental-pit-mat',
    name: 'Factory Effex Environmental FIM Pit Mat',
    price: 129,
    category: 'bike-stands-tools',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'bike-stands-tools'],
    brand: 'factory-effex',
    brandName: 'Factory Effex',
    badge: 'FIM Reg Approved',
    featured: true,
    isAccessory: true,
    images: [
      'https://images.unsplash.com/photo-1547038577-da80abbc4f19?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: 'FIM regulation compliant 200cm x 100cm absorbent fibrous top with impermeable non-slip rubber backing.',
    description: 'Compliant with Australian Motorcycling Federation (MA) and FIM environmental regulations. Protects garage floors, driveways, and pit paddocks from dirt, wash overflow, chain lube overspray, and battery coolant drips. Highly absorbent top nylon fibers soak up fluids while the oil-impermeable rubber backing prevents ground contamination.',
    specs: {
      Compliance: 'FIM Environmental Environmental Regulation & MA Compliant',
      Dimensions: '200cm x 100cm (Large Pit Footprint)',
      TopLayer: 'High-Density Absorbent UV-Resistant Nylon Carpet',
      Backing: 'Impermeable Anti-Slip Vulcanized Nitrile Rubber',
      Maintenance: 'Pressure-Washable & Chemical Resistant',
      Warranty: '1-Year Australian Warranty',
    },
  },

  // =========================================================================
  // SUB-CATEGORY 2: Transport & Hitch Carriers
  // =========================================================================
  {
    slug: 'ballards-heavy-duty-e-moto-hitch-carrier',
    name: "Ballard's Heavy-Duty E-Moto Tow Hitch Carrier",
    price: 349,
    category: 'storage-transport',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'storage-transport'],
    brand: 'ballards',
    brandName: "Ballard's Offroad",
    badge: '120kg Aussie Tow Spec',
    featured: true,
    isAccessory: true,
    images: [
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: 'Heavy-duty steel construction with 120kg capacity, integrated loading ramp, and anti-wobble stabilizer for 2" hitch receivers.',
    description: "Built tough for Australian outback corrugations and highway hauling. Ballard's E-Moto Hitch Carrier mounts securely into standard 50mm (2-inch) square towbar receivers. Rated to carry heavy electric dirt bikes up to 120kg including Surron, Talaria, E-Ride Pro, and Stark VARG with battery installed. Includes an attachable roll-on ramp and heavy-duty anti-tilt hitch clamp.",
    specs: {
      HitchCompatibility: 'Standard 50mm x 50mm (2-inch) Australian Towbar Receiver',
      MaxPayload: '120 kg Rated Capacity (Ideal for full-weight E-Motos)',
      Construction: 'Reinforced Powder-Coated High-Tensile Carbon Steel',
      Ramp: 'Detachable 1.1m Roll-On Steel Ramp Included with Wing-Nut Locking',
      Stabilizer: 'Heavy-Duty 3-Bolt Anti-Wobble / Anti-Rattle Hitch Collar Included',
      TieDownPoints: '4 Welded Steel Outrigger Tie-Down Loop Eyes',
      Weight: '22.5 kg',
      Warranty: '2-Year Australian Warranty',
    },
  },
  {
    slug: 'ballards-ratchet-tie-down-straps',
    name: "Ballard's Ratchet Tie-Down Straps with Soft Loops (Pair)",
    price: 49,
    category: 'storage-transport',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'storage-transport'],
    brand: 'ballards',
    brandName: "Ballard's Offroad",
    badge: '500kg Break Strength',
    featured: true,
    isAccessory: true,
    images: [
      'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1547038577-da80abbc4f19?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: 'Pair of 38mm wide heavy-duty tie-downs with built-in soft loops to prevent handlebar scratches, 500kg break strength.',
    description: "The gold standard for securing electric dirt bikes on utes, trailers, and vans. Ballard's 38mm ratchet tie-downs feature integrated soft-loop webbing extensions that wrap safely around delicate 28.6mm/31.8mm alloy handlebars and brake lines without scratching anodizing. Spring-loaded carabiner snap hooks on bottom prevent hook detachment over bumps.",
    specs: {
      WebbingWidth: '38mm (1.5 inch) High-Tensile Polyester Webbing',
      BreakStrength: '500 kg Rated Working Strength per Strap',
      IntegratedSoftLoop: 'Built-in 25cm Soft Loop Collar (No metal-to-handlebar contact)',
      BottomHooks: 'Spring-Loaded Heavy-Duty Carabiner Safety Snap Hooks',
      RatchetMechanism: 'Zinc-Plated Smooth Action Rubber-Grip Ratchet Lever',
      Quantity: 'Sold as a Matched Pair (2 Straps)',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'e-moto-heavy-duty-weatherproof-storage-cover',
    name: 'E-Moto Heavy-Duty Weatherproof Outdoor Cover',
    price: 69,
    category: 'storage-transport',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'storage-transport'],
    brand: 'e-moto-tech',
    brandName: 'E-Moto Tech',
    badge: '420D Oxford Shield',
    featured: false,
    isAccessory: true,
    images: ['/images/products/e-moto-heavy-duty-weatherproof-storage-cover.webp'],
    shortDescription: 'Heavy-duty 420D Oxford polyester with PU waterproof coating, lock security grommets, and heat-resistant battery cover panel.',
    description: 'Shield your prized electric dirt bike from intense Australian UV rays, rainstorms, and garage dust. Tailored to fit high-handlebar e-motos with front fenders. Features double-stitched taped seams, windproof under-frame buckle strap, elastic hem cords, and reinforced front lock grommets for chain cable locks.',
    specs: {
      Fabric: 'Heavy-Duty 420D Oxford Polyester with Waterproof Polyurethane (PU) Coating',
      UVProtection: 'UV50+ Australian Sun Degradation Protection',
      Waterproofing: 'Hydrostatic Head 3,000mm with Heat-Taped Seams',
      Security: 'Dual Reinforced Aluminum Anti-Theft Lock Holes at Front Wheel',
      Fitment: 'Universal Fit for Surron, Talaria, E-Ride Pro, Stark VARG & KTM Freeride',
      Warranty: '1-Year Australian Warranty',
    },
  },

  // =========================================================================
  // SUB-CATEGORY 3: Custom Graphics & Plastics Kits
  // =========================================================================
  {
    slug: 'backyard-design-surron-light-bee-custom-graphics-kit',
    name: 'Backyard Design 21mil Custom Graphics Kit for Surron Light Bee X',
    price: 199,
    category: 'graphics-plastics-kits',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'graphics-plastics-kits'],
    brand: 'backyard-design',
    brandName: 'Backyard Design',
    badge: '21 mil Armor Vinyl',
    featured: true,
    isAccessory: true,
    images: ['/images/products/backyard-design-surron-light-bee-custom-graphics-kit.webp'],
    shortDescription: 'Ultra-thick 21 mil moto-grade vinyl with sub-surface print, FLO air-release technology, and high-tack adhesive.',
    description: 'Transform your Surron Light Bee X with pro factory looks and heavy-duty scratch protection. Printed on sub-surface 21 mil armor vinyl with ultra-high-bond adhesive formulated specifically for low-surface-energy plastics and powder-coated frames. FLO technology micro-groove channels allow trapped air to escape easily during dry DIY installation without air bubbles.',
    specs: {
      Compatibility: 'Surron Light Bee X / Youth / Segway X160 / X260',
      VinylThickness: '21 mil (530 Micron) Heavy-Duty Off-Road Armor Grade',
      Adhesive: 'High-Bond Aggressive Moto Adhesive with FLO Air-Release Channels',
      KitCoverage: 'Battery Lid, Main Frame Spars, Front Fender, Rear Fender, Fork Guards, Swingarm',
      PrintQuality: 'Vibrant UV-Resistant High-Definition Eco-Solvent Inks',
      Warranty: '1-Year Fade & Adhesion Warranty',
    },
  },
  {
    slug: 'skda-factory-edition-graphics-kit-talaria-sting-mx4-mx5',
    name: 'SKDA Factory Edition Graphics Kit for Talaria Sting R / MX4 / MX5',
    price: 219,
    category: 'graphics-plastics-kits',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'graphics-plastics-kits'],
    brand: 'skda',
    brandName: 'SKDA Moto Graphics',
    badge: 'Aussie Custom Moto Decal',
    featured: true,
    isAccessory: true,
    images: [
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: 'Designed in Australia by SKDA with 20 mil high-gloss laminate, exact CNC die-cut template, and custom battery wrap.',
    description: 'Custom designed on the Australian coast by SKDA, leaders in world-class moto decal engineering. Custom-tailored specifically for the Talaria Sting R, MX4, and MX5 body lines. Features 20 mil ultra-durable laminate that withstands scrubbed tree branches, pressure washer blasts, and rocky roost without lifting.',
    specs: {
      Compatibility: 'Talaria Sting MX3, Sting R MX4 & Pro MX5',
      LaminateGrade: '20 mil Heavy-Duty Gloss Armor Laminate',
      DesignOrigin: 'Designed and Cut in Australia by SKDA',
      TemplatePrecision: 'Laser CNC Template for 100% Edge-to-Edge Contour Fit',
      IncludedSections: 'Front Fender, Number Plate, Shrouds, Battery Cover, Frame, Swingarm, Lower Fork Guards',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'polisport-restyle-front-fender-number-plate-kit',
    name: 'Polisport Restyle Front Fender & Number Plate Kit',
    price: 79,
    category: 'graphics-plastics-kits',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'graphics-plastics-kits'],
    brand: 'polisport',
    brandName: 'Polisport',
    badge: 'DGP Gloss Polymer',
    featured: false,
    isAccessory: true,
    images: [
      'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: 'Durable Gloss Polypropylene (DGP) restyle front fender and stadium number plate with universal bracket.',
    description: 'Upgrade the skinny OEM front fender on your Surron or Talaria to an aggressive full-size motocross look. Made from Polisport’s proprietary DGP (Durable Gloss Polypropylene) that flexes without snapping during crashes. Includes a stadium front number plate with mounting zip-ties and adapter brackets for inverted MTB/moto forks.',
    specs: {
      PlasticMaterial: 'DGP (Durable Gloss Polypropylene) High-Impact Flex Resin',
      Fitment: 'Universal Fit for Surron, Talaria, E-Ride Pro, 79Bike with inverted dual-crown forks',
      ColorOptions: 'Gloss Black / Factory White / Stealth Grey',
      MudProtection: 'Extended Rear Flare Deflects Mud from High-Voltage Headsets and Battery',
      Weight: '380 grams',
      Warranty: '1-Year Australian Warranty',
    },
  },

  // =========================================================================
  // SUB-CATEGORY 4: E-Moto Cleaning & Chain Lubes
  // =========================================================================
  {
    slug: 'muc-off-e-bike-clean-protect-lube-starter-bundle',
    name: 'Muc-Off E-Bike Clean, Protect & Lube Starter Kit',
    price: 69,
    category: 'maintenance-chemicals',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'maintenance-chemicals'],
    brand: 'muc-off',
    brandName: 'Muc-Off',
    badge: 'Complete Care Pack',
    featured: true,
    isAccessory: true,
    images: [
      'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1547038577-da80abbc4f19?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: 'Includes 1L Nano Tech Cleaner, 500ml MO-94 Moisture Displacer Spray, 50ml Dry E-Bike Chain Lube, Expanding Sponge & Brush.',
    description: 'The ultimate maintenance bundle formulated specifically for the high torque loads and sensitive electronics of modern electric dirt bikes. Muc-Off Nano Tech Cleaner cuts through baked-on clay without harming anodized finishes or rubber seals. MO-94 spray drives out residual moisture from electrical connectors and motor casings, while the Ceramic Dry E-Bike Lube reduces chain friction under massive instant electric torque.',
    specs: {
      KitContents: '1x 1L Nano Tech Bike Cleaner, 1x 500ml MO-94 Spray, 1x 50ml Dry E-Bike Ceramic Lube, 1x Microcell Expanding Sponge, 1x Soft Washing Brush',
      ElectricalSafety: 'Formulated safe for wiring harnesses, battery seals, and regenerative brake sensors',
      Environmental: 'Biodegradable, acid-free, CFC-free, and solvent-free formula',
      ChainCompatibility: 'Safe on 420 / 428 / 520 Standard, O-Ring and X-Ring Chains',
      Warranty: 'Quality Guaranteed by Muc-Off UK',
    },
  },
  {
    slug: 'motorex-off-road-chain-lube-cleaner-combo',
    name: 'Motorex Off-Road Chain Lube & Cleaner Kit',
    price: 49,
    category: 'maintenance-chemicals',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'maintenance-chemicals'],
    brand: 'motorex',
    brandName: 'Motorex Oil of Switzerland',
    badge: 'Swiss Pro Formula',
    featured: false,
    isAccessory: true,
    images: [
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: '500ml Motorex Chain Clean degreaser + 500ml Motorex Off-Road PTFE Chain Lube, O-ring & X-ring safe.',
    description: 'Handpicked by factory race teams worldwide. Motorex Chain Clean removes caked sand, grease, and chain wax in seconds without drying out internal O-rings or X-rings. Motorex Chain Lube Off-Road features high-pressure micro-synthetic PTFE additives that adhere stubbornly to rollers and sprockets even at top motor RPM, resisting water spray and Australian bull-dust.',
    specs: {
      Includes: '1x 500ml Motorex Chain Clean Degreaser + 1x 500ml Motorex Chain Lube Off-Road',
      Additives: 'Synthetic PTFE Micro-Film (Extreme Pressure & High-RPM Centrifugal Resistance)',
      RingSafety: '100% Tested & Approved for O-Ring, X-Ring, and Z-Ring Motorcycle Chains',
      Origin: 'Manufactured in Switzerland',
      Warranty: '100% Authentic Product Guarantee',
    },
  },
  {
    slug: 'muc-off-waterless-wash-750ml',
    name: 'Muc-Off High-Performance Waterless Wash (750ml)',
    price: 29,
    category: 'maintenance-chemicals',
    parentCategory: 'accessories',
    parentCategories: ['accessories', 'maintenance-chemicals'],
    brand: 'muc-off',
    brandName: 'Muc-Off',
    badge: 'E-Safe No Water Wash',
    featured: true,
    isAccessory: true,
    images: [
      'https://images.unsplash.com/photo-1547038577-da80abbc4f19?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: 'Non-sticky, streak-free formula that cleans without water, perfect for sensitive electrical motors and battery bays.',
    description: 'Never worry about high-pressure water blasting past electric motor seals, display screens, or battery terminals. Muc-Off Waterless Wash is an advanced spray cleaner that encapsulates dirt and grime on contact so you can wipe it off with a plush microfibre cloth without scratching your frame or graphics. Leaves a non-sticky, streak-free protective shine.',
    specs: {
      BottleSize: '750ml Spray Trigger Bottle',
      Application: 'Spray directly on dusty surfaces, let penetrate 1 minute, and wipe clean with microfibre cloth',
      ElectricalSafety: 'Ideal for rapid cleaning of high-voltage battery enclosures, throttle sensors, and controllers',
      Finish: 'Leaves a streak-free protective anti-static luster',
      Biodegradable: 'Eco-friendly biodegradable formulation',
      Warranty: 'Quality Guaranteed by Muc-Off',
    },
  },
];
