// src/config/ebikes.js
// Electric Dirt Bike models across our premier brands for the Australian market

export const EBIKES_DATA = [
  // 1. SURRON (5 models)
  {
    slug: 'surron-light-bee-x-lbx',
    name: 'Surron Light Bee X (LBX)',
    brand: 'surron',
    brandName: 'Surron',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 7490,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '60V',
      PeakPower: '6 kW Peak',
      Battery: '40Ah (2,400 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '75 km/h',
      Range: 'Up to 75 km',
      Weight: '56 kg',
    },
    images: ['/images/products/surron-light-bee-x-lbx.webp'],
    shortDescription: 'The world-famous agile electric trail bike featuring 6kW peak power, 60V 40Ah battery, and forged aluminium alloy frame.',
    description: 'The Surron Light Bee X (LBX) is Australia’s benchmark lightweight electric trail weapon. Combining mountain-bike flickability with 250Nm of instantaneous rear-wheel torque, the LBX conquers steep bush singletrack, sand dunes, and motocross berms with zero clutch maintenance.',
  },
  {
    slug: 'surron-ultra-bee',
    name: 'Surron Ultra Bee',
    brand: 'surron',
    brandName: 'Surron',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 9990,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '74V',
      PeakPower: '12.5 kW Peak',
      Battery: '55Ah (4,070 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '90 km/h',
      Range: 'Up to 140 km',
      Weight: '85 kg',
    },
    images: ['/images/products/surron-ultra-bee.webp'],
    shortDescription: 'Mid-weight enduro electric bike with 74V 55Ah powerpack, 12.5 kW peak power, Surron Traction Control (SRTC), and 440Nm torque.',
    description: 'Surron Ultra Bee bridges the gap between lightweight e-motos and full-sized 450cc four-strokes. Featuring an integrated 74V 55Ah lithium powerpack, regenerative multi-tier engine braking, and high-performance 37mm inverted front forks.',
  },
  {
    slug: 'surron-storm-bee-enduro',
    name: 'Surron Storm Bee Enduro',
    brand: 'surron',
    brandName: 'Surron',
    category: 'full-size-motocross',
    subcategoryName: 'Full-Size Motocross',
    price: 14990,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '96V',
      PeakPower: '22.5 kW Peak',
      Battery: '48Ah (4,608 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '110 km/h',
      Range: 'Up to 100 km',
      Weight: '127 kg',
    },
    images: ['/images/products/surron-storm-bee-enduro.webp'],
    shortDescription: 'Heavyweight full-size 96V electric motocross machine delivering 22.5kW peak power, 520Nm rear-wheel torque, and 21"/18" full MX wheels.',
    description: 'The Surron Storm Bee Enduro is engineered for uncompromising motocross performance. Boasting a liquid-cooled motor and a 96V high-voltage architecture, it delivers earth-shredding holeshots with zero shifting or clutch fade.',
  },
  {
    slug: 'surron-ultra-bee-road-adr',
    name: 'Surron Ultra Bee Road (ADR L1e)',
    brand: 'surron',
    brandName: 'Surron',
    category: 'adr-road-legal-dirt-bikes',
    subcategoryName: 'ADR Road-Legal Dirt Bikes',
    price: 10490,
    roadLegal: true,
    target: 'Adult',
    badge: 'Road Legal (ADR)',
    featured: true,
    specs: {
      Voltage: '74V',
      PeakPower: '12.5 kW Peak',
      Battery: '55Ah (4,070 Wh)',
      RoadLegal: 'Yes (ADR Compliant)',
      TargetAudience: 'Adult',
      TopSpeed: '90 km/h',
      Range: 'Up to 140 km',
      Weight: '88 kg',
    },
    images: ['/images/products/surron-ultra-bee-road-adr.webp'],
    shortDescription: 'Australian Design Rules (ADR) street-legal electric dirt bike with dual-sport road gear, mirrors, indicators, horn, and rego compliance.',
    description: 'Fully road registerable across all Australian states (QLD, NSW, VIC, WA, SA, TAS, NT). The Ultra Bee Road L1e lets you commute during the week and conquer rugged off-road forestry trails on the weekend without needing a ute or trailer.',
  },
  {
    slug: 'surron-hyper-bee',
    name: 'Surron Hyper Bee',
    brand: 'surron',
    brandName: 'Surron',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 3990,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '48V',
      PeakPower: '5 kW Peak',
      Battery: '25Ah (1,200 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '50 km/h',
      Range: 'Up to 50 km',
      Weight: '38 kg',
    },
    images: ['/images/products/surron-hyper-bee.webp'],
    shortDescription: 'High-performance youth electric dirt bike with 48V architecture, selectable power governor modes, and ultra-lightweight 38kg chassis.',
    description: 'The Surron Hyper Bee is the ultimate transition bike for growing junior riders. Offering selectable parent speed limiters, progressive hydraulic disc brakes, and race-tuned suspension.',
  },

  // 2. TALARIA (5 models)
  {
    slug: 'talaria-sting-r-mx4',
    name: 'Talaria Sting R MX4',
    brand: 'talaria',
    brandName: 'Talaria',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 6500,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '60V',
      PeakPower: '8 kW Peak',
      Battery: '45Ah (2,700 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '85 km/h',
      Range: 'Up to 85 km',
      Weight: '63 kg',
    },
    images: ['/images/products/talaria-sting-r-mx4.webp'],
    shortDescription: 'Gearbox-driven 60V 8kW electric dirt bike with sealed oil-bath primary transmission, IPM motor, and zero primary belt failures.',
    description: 'The Talaria Sting R MX4 is built for tough Australian bush conditions where mud, sticks, and grit destroy rubber belt drives. Its enclosed helical gearbox ensures bulletproof power transfer and relentless throttle response.',
  },
  {
    slug: 'talaria-sting-pro-mx5',
    name: 'Talaria Sting Pro MX5',
    brand: 'talaria',
    brandName: 'Talaria',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 7500,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '72V',
      PeakPower: '13.5 kW Peak',
      Battery: '40Ah (2,880 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '95 km/h',
      Range: 'Up to 100 km',
      Weight: '67 kg',
    },
    images: ['/images/products/talaria-sting-pro-mx5.webp'],
    shortDescription: 'Flagship 72V 13.5kW factory hot-rod with 500Nm wheel torque, upgraded FastAce inverted forks, and oversized DOT brake rotors.',
    description: 'The Talaria Sting Pro MX5 steps straight into 72V territory with 13.5kW of peak brushless punch. Designed to out-accelerate traditional 250cc 4-strokes on technical hills and loose shale.',
  },
  {
    slug: 'talaria-x3-concept-xxx',
    name: 'Talaria X3 Concept (XXX)',
    brand: 'talaria',
    brandName: 'Talaria',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 5500,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '60V',
      PeakPower: '5.5 kW Peak',
      Battery: '40Ah (2,400 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '75 km/h',
      Range: 'Up to 80 km',
      Weight: '58 kg',
    },
    images: ['/images/products/talaria-x3-concept-xxx.webp'],
    shortDescription: 'Ultra-compact lightweight trail moto featuring 60V 40Ah battery, minimalist chassis geometry, and instant electric throttle response.',
    description: 'The Talaria X3 Concept (XXX) delivers unbeatable value and nimble handling. Perfect for trail sessions, pump tracks, and tight singletrack lines.',
  },
  {
    slug: 'talaria-komodo',
    name: 'Talaria Komodo',
    brand: 'talaria',
    brandName: 'Talaria',
    category: 'full-size-motocross',
    subcategoryName: 'Full-Size Motocross',
    price: 9000,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '84V',
      PeakPower: '22 kW Peak',
      Battery: '50Ah (4,200 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '115 km/h',
      Range: 'Up to 110 km',
      Weight: '92 kg',
    },
    images: ['/images/products/talaria-komodo.webp'],
    shortDescription: 'High-voltage 84V full-size electric motocross contender producing 22kW peak power, link-type rear suspension, and 21"/18" wheelset.',
    description: 'The Talaria Komodo enters the full-size competition arena with an 84V architecture and 22kW output. Full-size motocross ergonomics and heavy-duty frame design.',
  },
  {
    slug: 'talaria-sting-l1e-road-legal',
    name: 'Talaria Sting L1e Road Legal',
    brand: 'talaria',
    brandName: 'Talaria',
    category: 'adr-road-legal-dirt-bikes',
    subcategoryName: 'ADR Road-Legal Dirt Bikes',
    price: 7500,
    roadLegal: true,
    target: 'Adult',
    badge: 'Road Legal (ADR)',
    featured: false,
    specs: {
      Voltage: '60V',
      PeakPower: '3.5 kW Peak',
      Battery: '38Ah (2,280 Wh)',
      RoadLegal: 'Yes (ADR Compliant)',
      TargetAudience: 'Adult',
      TopSpeed: '50 km/h (Moped/L1e)',
      Range: 'Up to 70 km',
      Weight: '66 kg',
    },
    images: ['/images/products/talaria-sting-l1e-road-legal.webp'],
    shortDescription: 'ADR-compliant road-legal dual-sport electric dirt bike with full LED light package, horn, dual mirrors, and Australian road registration kit.',
    description: 'The Talaria Sting L1e is road registered for street and bush riding across Australia. Perfect for commuting to school, university, or work, with the freedom to hit dirt trails on the way home.',
  },

  // 3. STARK FUTURE (5 models)
  {
    slug: 'stark-varg-mx-60hp',
    name: 'Stark VARG MX (60hp)',
    brand: 'stark-future',
    brandName: 'Stark Future',
    category: 'full-size-motocross',
    subcategoryName: 'Full-Size Motocross',
    price: 18990,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '360V',
      PeakPower: '45 kW (60 hp)',
      Battery: '6.5 kWh Magnesium Pack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '130 km/h',
      Range: 'Up to 6 hours trail / Pro MX moto',
      Weight: '118 kg',
    },
    images: ['/images/products/stark-varg-mx-60hp.webp'],
    shortDescription: 'The 60hp Swedish electric motocross revolution with 360V carbon-sleeve motor, 938Nm wheel torque, and smartphone power curve tuning.',
    description: 'The Stark VARG MX 60hp delivers track performance rivaling 450cc four-strokes. Featuring custom KYB suspension, military-grade smartphone display, and customizable power maps from 10hp to 60hp.',
  },
  {
    slug: 'stark-varg-alpha-mx-80hp',
    name: 'Stark VARG Alpha MX (80hp)',
    brand: 'stark-future',
    brandName: 'Stark Future',
    category: 'full-size-motocross',
    subcategoryName: 'Full-Size Motocross',
    price: 19990,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '360V',
      PeakPower: '60 kW (80 hp)',
      Battery: '6.5 kWh Magnesium Pack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '135 km/h',
      Range: 'Up to 6 hours trail / Pro MX moto',
      Weight: '118 kg',
    },
    images: ['/images/products/stark-varg-alpha-mx-80hp.webp'],
    shortDescription: 'World’s most powerful motocross bike generating 80hp, 938Nm wheel torque, Brembo brakes, and custom-valved KYB factory suspension.',
    description: 'The Stark VARG Alpha MX 80hp is the pinnacle of two-wheel electric power. With 80 horsepower in an ultra-compact chassis, it delivers acceleration that leaves traditional four-stroke 450s behind.',
  },
  {
    slug: 'stark-varg-mx-12',
    name: 'Stark VARG MX 1.2',
    brand: 'stark-future',
    brandName: 'Stark Future',
    category: 'full-size-motocross',
    subcategoryName: 'Full-Size Motocross',
    price: 20490,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '360V',
      PeakPower: '60 kW (80 hp)',
      Battery: '7.2 kWh Extended Capacity',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '135 km/h',
      Range: 'Up to 7.5 hours trail / Extended MX',
      Weight: '121 kg',
    },
    images: ['/images/products/stark-varg-mx-12.webp'],
    shortDescription: 'Extended-range 7.2 kWh battery edition of the 80hp Stark VARG MX for long-distance off-road endurance and race motos.',
    description: 'Featuring Stark’s newest 7.2 kWh honeycomb magnesium pack, the VARG MX 1.2 provides extended track and trail runtime without compromising center-of-gravity balance.',
  },
  {
    slug: 'stark-varg-ex-enduro',
    name: 'Stark VARG EX Enduro',
    brand: 'stark-future',
    brandName: 'Stark Future',
    category: 'adr-road-legal-dirt-bikes',
    subcategoryName: 'ADR Road-Legal Dirt Bikes',
    price: 20990,
    roadLegal: true,
    target: 'Adult',
    badge: 'Road Legal (ADR)',
    featured: true,
    specs: {
      Voltage: '360V',
      PeakPower: '60 kW (80 hp)',
      Battery: '6.5 kWh Magnesium Pack',
      RoadLegal: 'Yes (ADR Compliant)',
      TargetAudience: 'Adult',
      TopSpeed: '130 km/h',
      Range: 'Up to 6 hours enduro trail',
      Weight: '122 kg',
    },
    images: ['/images/products/stark-varg-ex-enduro.webp'],
    shortDescription: 'ADR road-legal 80hp electric enduro motorcycle with headlight, tail-tidy, horn, sidemirrors, and full Australian road compliance.',
    description: 'The Stark VARG EX Enduro combines Australian street-legal compliance with pro-level 80hp motocross power. Ride from your suburban garage directly into the national state forest singletrack.',
  },
  {
    slug: 'stark-varg-sm-supermoto',
    name: 'Stark VARG SM Supermoto',
    brand: 'stark-future',
    brandName: 'Stark Future',
    category: 'adr-road-legal-dirt-bikes',
    subcategoryName: 'ADR Road-Legal Dirt Bikes',
    price: 22990,
    roadLegal: true,
    target: 'Adult',
    badge: 'Road Legal (ADR)',
    featured: true,
    specs: {
      Voltage: '360V',
      PeakPower: '60 kW (80 hp)',
      Battery: '6.5 kWh Magnesium Pack',
      RoadLegal: 'Yes (ADR Compliant)',
      TargetAudience: 'Adult',
      TopSpeed: '145 km/h',
      Range: 'Up to 150 km road riding',
      Weight: '124 kg',
    },
    images: ['/images/products/stark-varg-sm-supermoto.webp'],
    shortDescription: 'The ultimate 80hp electric supermoto with 17" forged wheels, sticky Pirelli Diablo Rosso IV tyres, and oversized 320mm Brembo front disc.',
    description: 'The flagship Stark VARG SM Supermoto represents the pinnacle of street-legal electric motard performance in Australia. Unrivaled cornering grip and blisteringly fast road acceleration.',
  },

  // 4. E RIDE PRO (5 models)
  {
    slug: 'e-ride-pro-ss-20',
    name: 'E Ride Pro-SS 2.0',
    brand: 'e-ride-pro',
    brandName: 'E Ride Pro',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 7490,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '72V',
      PeakPower: '12 kW Peak',
      Battery: '40Ah (2,880 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '90 km/h',
      Range: 'Up to 90 km',
      Weight: '62 kg',
    },
    images: ['/images/products/e-ride-pro-ss-20.webp'],
    shortDescription: 'Out-of-the-box 72V 12kW electric dirt bike with Samsung 50S high-drain battery, inverted hydraulic fork, and rapid acceleration.',
    description: 'The E Ride Pro-SS 2.0 delivered the high-voltage revolution directly to trail riders without needing costly aftermarket upgrades. 72V factory power, beefy swingarm, and CNC footpeg brackets.',
  },
  {
    slug: 'e-ride-pro-ss-30',
    name: 'E Ride Pro-SS 3.0',
    brand: 'e-ride-pro',
    brandName: 'E Ride Pro',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 7990,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '72V',
      PeakPower: '12.5 kW Peak',
      Battery: '40Ah (2,880 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '95 km/h',
      Range: 'Up to 95 km',
      Weight: '64 kg',
    },
    images: ['/images/products/e-ride-pro-ss-30.webp'],
    shortDescription: 'Next-gen 72V 12.5kW high-output dirt bike with reinforced gearbox, upgraded air-adjustable suspension, and heavy-duty 4-piston calipers.',
    description: 'The updated E Ride Pro-SS 3.0 builds upon the proven 72V platform with enhanced thermal dissipation, heavy-duty spoke wheels, and refined throttle mapping.',
  },
  {
    slug: 'e-ride-pro-s',
    name: 'E Ride Pro-S',
    brand: 'e-ride-pro',
    brandName: 'E Ride Pro',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 5990,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '72V',
      PeakPower: '6 kW Peak',
      Battery: '30Ah (2,160 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '75 km/h',
      Range: 'Up to 70 km',
      Weight: '55 kg',
    },
    images: ['/images/products/e-ride-pro-s.webp'],
    shortDescription: 'Entry 72V lightweight trail moto delivering 6kW peak power, agile 55kg dry weight, and progressive hydraulic brakes.',
    description: 'The E Ride Pro-S brings 72V high-efficiency architecture into a lightweight, accessible package that riders of any experience level can handle with confidence.',
  },
  {
    slug: 'e-ride-pro-sr-enduro',
    name: 'E Ride Pro-SR Enduro',
    brand: 'e-ride-pro',
    brandName: 'E Ride Pro',
    category: 'full-size-motocross',
    subcategoryName: 'Full-Size Motocross',
    price: 9490,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '72V',
      PeakPower: '25 kW Peak',
      Battery: '50Ah (3,600 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '115 km/h',
      Range: 'Up to 110 km',
      Weight: '85 kg',
    },
    images: ['/images/products/e-ride-pro-sr-enduro.webp'],
    shortDescription: 'Full-size 25kW peak electric race machine with 72V 50Ah power, 21"/18" dirt rims, and 280mm travel suspension.',
    description: 'The Pro-SR Enduro is E Ride Pro’s top-tier competition motocross bike. Featuring 25kW peak power and 540Nm rear-wheel torque, built for open scrub, jumps, and hill climbs.',
  },
  {
    slug: 'e-ride-pro-s-supermoto-edition',
    name: 'E Ride Pro-S Supermoto Edition',
    brand: 'e-ride-pro',
    brandName: 'E Ride Pro',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 6390,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '72V',
      PeakPower: '6 kW Peak',
      Battery: '30Ah (2,160 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '80 km/h',
      Range: 'Up to 75 km',
      Weight: '56 kg',
    },
    images: ['/images/products/e-ride-pro-s-supermoto-edition.webp'],
    shortDescription: 'Factory supermoto build with 17-inch road wheels, performance street rubber, low center of gravity, and 72V high-efficiency drive.',
    description: 'Designed for kart tracks, parking lot gymkhana, and tight bitumen circuits, the Pro-S Supermoto Edition combines low-drag rolling efficiency with instantaneous electric punch.',
  },

  // 5. KTM (5 models)
  {
    slug: 'ktm-freeride-e-xc',
    name: 'KTM Freeride E-XC',
    brand: 'ktm',
    brandName: 'KTM',
    category: 'full-size-motocross',
    subcategoryName: 'Full-Size Motocross',
    price: 17495,
    roadLegal: true,
    target: 'Adult',
    badge: 'Road Legal (ADR)',
    featured: true,
    specs: {
      Voltage: '260V',
      PeakPower: '18 kW Peak',
      Battery: '3.9 kWh PowerPack',
      RoadLegal: 'Yes (ADR Compliant)',
      TargetAudience: 'Adult',
      TopSpeed: '95 km/h',
      Range: 'Up to 2 hours enduro ride',
      Weight: '111 kg',
    },
    images: ['/images/products/ktm-freeride-e-xc.webp'],
    shortDescription: 'Championship-winning European electric enduro bike with 260V architecture, WP XPLOR suspension, and full ADR road registration.',
    description: 'The KTM Freeride E-XC embodies Austrian competition pedigree. Premium WP suspension components, Formula brakes, and zero local emissions with full Australian street-legal compliance.',
  },
  {
    slug: 'ktm-sx-e-5',
    name: 'KTM SX-E 5',
    brand: 'ktm',
    brandName: 'KTM',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 8490,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '48V',
      PeakPower: '5 kW Peak',
      Battery: '907 Wh Lithium-Ion',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '45 km/h (Adjustable)',
      Range: 'Up to 2 hours beginner / 25 min race',
      Weight: '40.5 kg',
    },
    images: ['/images/products/ktm-sx-e-5.webp'],
    shortDescription: 'High-end youth electric motocross bike competing in 50cc junior classes with WP XACT air forks and adjustable seat height.',
    description: 'The KTM SX-E 5 is the premier junior electric racer in Australia. Fitted with WP air suspension, customizable power maps from gentle learner to full-race 5kW, and adjustable frame height.',
  },
  {
    slug: 'ktm-sx-e-3',
    name: 'KTM SX-E 3',
    brand: 'ktm',
    brandName: 'KTM',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 6990,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '48V',
      PeakPower: '3.8 kW Peak',
      Battery: '648 Wh Lithium-Ion',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '35 km/h',
      Range: 'Up to 2 hours riding',
      Weight: '39 kg',
    },
    images: ['/images/products/ktm-sx-e-3.webp'],
    shortDescription: 'Junior starter electric dirt bike with 3.8kW motor, low seat height, sealed battery pack, and non-intimidating power curve.',
    description: 'The KTM SX-E 3 is engineered for groms aged 4-8 stepping up from balance bikes. Safe, clean, whisper-quiet electric motocross thrills.',
  },
  {
    slug: 'ktm-sx-e-2',
    name: 'KTM SX-E 2',
    brand: 'ktm',
    brandName: 'KTM',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 3690,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '36V',
      PeakPower: '1.8 kW Peak',
      Battery: '290 Wh Removable PowerPack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '33 km/h',
      Range: 'Up to 100 minutes',
      Weight: '29 kg',
    },
    images: ['/images/products/ktm-sx-e-2.webp'],
    shortDescription: 'Mini electric dirt bike featuring 1.8kW hub-less power, 36V architecture, disc brakes, and easy-swap quick-disconnect battery.',
    description: 'Designed as the bridge between electric balance bikes and full-size junior racers. The SX-E 2 gives young riders genuine moto ergonomics with zero exhaust pipe burn risk.',
  },
  {
    slug: 'ktm-sx-e-116-balance-bike',
    name: 'KTM SX-E 1.16 Balance Bike',
    brand: 'ktm',
    brandName: 'KTM',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 1490,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '20V',
      PeakPower: '350W',
      Battery: '4Ah Lithium Quick-Release',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '18 km/h',
      Range: 'Up to 60 minutes',
      Weight: '9 kg',
    },
    images: [
      'https://images.unsplash.com/photo-1547038577-da80abbc4f19?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
    ],
    shortDescription: '16-inch electric balance bike for kids aged 4-8 with 3 power modes, twist throttle, and lightweight composite frame.',
    description: 'The KTM SX-E 1.16 teaches essential balance, braking, and throttle control. Features authentic KTM Factory Racing graphics and pneumatic off-road tyres.',
  },

  // 6. HUSQVARNA (5 models)
  {
    slug: 'husqvarna-ee-5',
    name: 'Husqvarna EE 5',
    brand: 'husqvarna',
    brandName: 'Husqvarna',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 8690,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '48V',
      PeakPower: '5 kW Peak',
      Battery: '907 Wh High-Capacity Pack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '45 km/h',
      Range: 'Up to 2 hours beginner / 25 min race',
      Weight: '40.5 kg',
    },
    images: ['/images/products/husqvarna-ee-5.webp'],
    shortDescription: 'Swedish-styled competition junior electric motocross bike with 5kW output, WP XACT air suspension, and adjustable ergonomic cockpit.',
    description: 'Husqvarna EE 5 is engineered for junior competitive motocross racing. Clean Scandinavian styling, zero emissions, and WP XACT air suspension matched with 6 selectable ride modes.',
  },
  {
    slug: 'husqvarna-ee-3',
    name: 'Husqvarna EE 3',
    brand: 'husqvarna',
    brandName: 'Husqvarna',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 7190,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '48V',
      PeakPower: '3.8 kW Peak',
      Battery: '648 Wh Lithium-Ion',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '35 km/h',
      Range: 'Up to 2 hours riding',
      Weight: '39 kg',
    },
    images: ['/images/products/husqvarna-ee-3.webp'],
    shortDescription: 'Junior entry electric bike featuring 3.8kW electric power, manageable seat height, WP suspension, and rollover safety sensor.',
    description: 'The Husqvarna EE 3 offers safe, accessible entry into dirt riding with advanced safety features including a roll-over sensor that immediately shuts off power.',
  },
  {
    slug: 'husqvarna-ee-2',
    name: 'Husqvarna EE 2',
    brand: 'husqvarna',
    brandName: 'Husqvarna',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 3790,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '36V',
      PeakPower: '1.8 kW Peak',
      Battery: '290 Wh Removable Pack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '33 km/h',
      Range: 'Up to 100 minutes',
      Weight: '29 kg',
    },
    images: ['/images/products/husqvarna-ee-2.webp'],
    shortDescription: 'Youth mini electric dirt bike with WP hydraulic fork, disc brakes, and quick-swap 36V power system.',
    description: 'Bridging the gap between balance bikes and 50cc competitors, the EE 2 gives young riders full throttle confidence in a lightweight chassis.',
  },
  {
    slug: 'husqvarna-ee-116',
    name: 'Husqvarna EE 1.16',
    brand: 'husqvarna',
    brandName: 'Husqvarna',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 1550,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '20V',
      PeakPower: '350W',
      Battery: '4Ah High-Output',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '18 km/h',
      Range: 'Up to 60 minutes',
      Weight: '9.3 kg',
    },
    images: ['/images/products/husqvarna-ee-116.webp'],
    shortDescription: '16-inch electric balance bike with aluminum frame, twist throttle, and 3 parental speed modes.',
    description: 'The Husqvarna EE 1.16 is the ideal learning platform for young kids progressing toward pedal-less balance and throttle mastery.',
  },
  {
    slug: 'husqvarna-ee-112',
    name: 'Husqvarna EE 1.12',
    brand: 'husqvarna',
    brandName: 'Husqvarna',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 1150,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '20V',
      PeakPower: '250W',
      Battery: '2Ah Quick-Release',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '14 km/h',
      Range: 'Up to 50 minutes',
      Weight: '7.7 kg',
    },
    images: ['/images/products/husqvarna-ee-112.webp'],
    shortDescription: '12-inch entry e-balance bike for toddlers aged 3-5 with composite wheels and non-marking rubber tires.',
    description: 'The lightest electric balance bike in the Husqvarna range. Perfect for backyard grass, footpaths, and pump tracks.',
  },

  // 7. GASGAS (5 models)
  {
    slug: 'gasgas-mc-e-5',
    name: 'GASGAS MC-E 5',
    brand: 'gasgas',
    brandName: 'GASGAS',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 8290,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '48V',
      PeakPower: '5 kW Peak',
      Battery: '907 Wh PowerPack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '45 km/h',
      Range: 'Up to 2 hours beginner / 25 min race',
      Weight: '40.5 kg',
    },
    images: ['/images/products/gasgas-mc-e-5.webp'],
    shortDescription: 'All-red Spanish-styled junior electric motocross racer with 5kW motor, WP XACT suspension, and Maxxis tyres.',
    description: 'The GASGAS MC-E 5 brings the vibrant red racing energy of GASGAS to the electric junior circuit. Adjustable power modes, robust chromoly steel frame, and WP air forks.',
  },
  {
    slug: 'gasgas-mc-e-3',
    name: 'GASGAS MC-E 3',
    brand: 'gasgas',
    brandName: 'GASGAS',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 6790,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '48V',
      PeakPower: '3.8 kW Peak',
      Battery: '648 Wh Lithium-Ion',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '35 km/h',
      Range: 'Up to 2 hours riding',
      Weight: '39 kg',
    },
    images: ['/images/products/gasgas-mc-e-3.webp'],
    shortDescription: 'Intermediate youth e-dirt bike with 3.8kW electric power, low standover height, and lanyard safety cut-off.',
    description: 'The GASGAS MC-E 3 is engineered for groms ready to graduate into serious dirt track practice. Quiet, clean, and ultra-durable.',
  },
  {
    slug: 'gasgas-mc-e-2',
    name: 'GASGAS MC-E 2',
    brand: 'gasgas',
    brandName: 'GASGAS',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 3490,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '36V',
      PeakPower: '1.8 kW Peak',
      Battery: '290 Wh Removable Pack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '33 km/h',
      Range: 'Up to 100 minutes',
      Weight: '29 kg',
    },
    images: ['/images/products/gasgas-mc-e-2.webp'],
    shortDescription: 'Youth mini electric moto with WP suspension, disc brakes, and race-inspired GASGAS graphics.',
    description: 'The MC-E 2 offers a thrilling platform for developing riders, featuring adjustable power output and a lightweight chassis.',
  },
  {
    slug: 'gasgas-mc-e-116-balance-bike',
    name: 'GASGAS MC-E 1.16 Balance Bike',
    brand: 'gasgas',
    brandName: 'GASGAS',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 1450,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '20V',
      PeakPower: '350W',
      Battery: '4Ah Lithium Battery',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '18 km/h',
      Range: 'Up to 60 minutes',
      Weight: '9 kg',
    },
    images: ['/images/products/gasgas-mc-e-116-balance-bike.webp'],
    shortDescription: '16-inch electric balance bike with twist throttle and 3 speed modes for children learning two-wheel coordination.',
    description: 'Get the little ones rippin’ early on the GASGAS MC-E 1.16. Robust aluminium construction and pneumatic knobby tyres.',
  },
  {
    slug: 'gasgas-mc-e-112-balance-bike',
    name: 'GASGAS MC-E 1.12 Balance Bike',
    brand: 'gasgas',
    brandName: 'GASGAS',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 1050,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '20V',
      PeakPower: '250W',
      Battery: '2Ah Quick-Release',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '14 km/h',
      Range: 'Up to 50 minutes',
      Weight: '7.7 kg',
    },
    images: ['/images/products/gasgas-mc-e-112-balance-bike.webp'],
    shortDescription: '12-inch entry-level electric balance bike with low seat height and smooth electric assist for toddlers.',
    description: 'The GASGAS MC-E 1.12 provides the safest and most enjoyable entry into the world of motorcycling for toddlers aged 3-5.',
  },

  // 8. KUBERG (5 models)
  {
    slug: 'kuberg-freerider',
    name: 'Kuberg Freerider',
    brand: 'kuberg',
    brandName: 'Kuberg',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 8990,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '48V',
      PeakPower: '12 kW Peak',
      Battery: '22.2Ah (1,065 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '65 km/h',
      Range: 'Up to 60 km',
      Weight: '36 kg',
    },
    images: ['/images/products/kuberg-freerider.webp'],
    shortDescription: 'Ultra-lightweight 36kg European electric freeride bike with 12kW peak power and bicycle-like flickability.',
    description: 'Handcrafted in Europe, the Kuberg Freerider offers an unmatched power-to-weight ratio. At just 36kg, it lets riders Bunny-hop obstacles and carve mountain lines impossible on heavier bikes.',
  },
  {
    slug: 'kuberg-cross-hero',
    name: 'Kuberg Cross Hero',
    brand: 'kuberg',
    brandName: 'Kuberg',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 3890,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '36V',
      PeakPower: '3 kW Peak',
      Battery: '12Ah (432 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '27 km/h',
      Range: 'Up to 2 hours riding',
      Weight: '33 kg',
    },
    images: ['/images/products/kuberg-cross-hero.webp'],
    shortDescription: 'Youth electric motocross bike with 3kW motor, double-cradle steel frame, and smartphone parental tuning app.',
    description: 'The Kuberg Cross Hero is precision-built for young riders aged 5-12. Features Bluetooth app integration allowing parents to set speed limits and perimeter geo-fences.',
  },
  {
    slug: 'kuberg-trial-hero',
    name: 'Kuberg Trial Hero',
    brand: 'kuberg',
    brandName: 'Kuberg',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 3690,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '36V',
      PeakPower: '3 kW Peak',
      Battery: '12Ah (432 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '27 km/h',
      Range: 'Up to 2 hours riding',
      Weight: '31 kg',
    },
    images: ['/images/products/kuberg-trial-hero.webp'],
    shortDescription: 'Junior electric trials bike without a seat, designed for precision balance, technical hopping, and obstacle control.',
    description: 'The Kuberg Trial Hero instills master-level balance and clutchless low-speed throttle finesse for junior trials competition.',
  },
  {
    slug: 'kuberg-start',
    name: 'Kuberg Start',
    brand: 'kuberg',
    brandName: 'Kuberg',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 2790,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '24V',
      PeakPower: '1 kW Peak',
      Battery: '9Ah (216 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '24 km/h',
      Range: 'Up to 1 hour',
      Weight: '21 kg',
    },
    images: ['/images/products/kuberg-start.webp'],
    shortDescription: 'First electric bike for groms aged 3-5 with fully enclosed battery and drive chain for safety.',
    description: 'The Kuberg Start provides a lightweight, confidence-inspiring stepping stone into motorized dirt biking with zero hot surfaces.',
  },
  {
    slug: 'kuberg-ranger-utility',
    name: 'Kuberg Ranger Utility',
    brand: 'kuberg',
    brandName: 'Kuberg',
    category: 'utility-farm-e-bikes',
    subcategoryName: 'Utility & Farm E-Bikes',
    price: 9490,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '48V',
      PeakPower: '14 kW Peak',
      Battery: '24Ah (1,152 Wh) Dual Pack Option',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '80 km/h',
      Range: 'Up to 100 km',
      Weight: '50 kg',
    },
    images: ['/images/products/kuberg-ranger-utility.webp'],
    shortDescription: 'Multifunctional electric utility bike with pneumatic standing seat, 14kW peak power, and cargo hauling capabilities.',
    description: 'The Kuberg Ranger Utility features a unique pneumatically liftable seat that drops flat for standing trials riding or raises for comfortable seated paddock navigation.',
  },

  // 9. OSET (5 models)
  {
    slug: 'oset-240-racing',
    name: 'OSET 24.0 Racing',
    brand: 'oset',
    brandName: 'OSET',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 6490,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '48V',
      PeakPower: '1.4 kW Peak',
      Battery: '20Ah Lithium Pack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '38 km/h',
      Range: 'Up to 3 hours trials riding',
      Weight: '46 kg',
    },
    images: ['/images/products/oset-240-racing.webp'],
    shortDescription: 'Championship-winning 24-inch electric trials bike with adjustable dials for speed, power, and throttle response.',
    description: 'The OSET 24.0 Racing is the weapon of choice for teenage and adult trials riders. Fine-tune power, response, and top speed independently via 3 onboard dials.',
  },
  {
    slug: 'oset-200-racing-mkii',
    name: 'OSET 20.0 Racing MKII',
    brand: 'oset',
    brandName: 'OSET',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 4990,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '48V',
      PeakPower: '1.2 kW Peak',
      Battery: '20Ah Lithium Battery',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '32 km/h',
      Range: 'Up to 3 hours trials riding',
      Weight: '37 kg',
    },
    images: ['/images/products/oset-200-racing-mkii.webp'],
    shortDescription: '20-inch competition electric trials bike for riders aged 8-12 with hydraulic disc brakes and alloy swingarm.',
    description: 'The benchmark in competitive youth trials. The OSET 20.0 Racing MKII provides instant throttle control to hop logs, rocks, and steep gullies.',
  },
  {
    slug: 'oset-160-racing',
    name: 'OSET 16.0 Racing',
    brand: 'oset',
    brandName: 'OSET',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 3690,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '36V',
      PeakPower: '800W Peak',
      Battery: '10Ah Lithium Battery',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '25 km/h',
      Range: 'Up to 2 hours',
      Weight: '29 kg',
    },
    images: ['/images/products/oset-160-racing.webp'],
    shortDescription: '16-inch junior electric trials bike for riders aged 5-7 with padded bar wrap, dual disc brakes, and full chain guard.',
    description: 'The OSET 16.0 Racing introduces youngsters to obstacle-based riding with confidence, safety, and customizable dials.',
  },
  {
    slug: 'oset-125-racing',
    name: 'OSET 12.5 Racing',
    brand: 'oset',
    brandName: 'OSET',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 2490,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '24V',
      PeakPower: '600W Peak',
      Battery: '8Ah Battery Pack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '20 km/h',
      Range: 'Up to 90 minutes',
      Weight: '24 kg',
    },
    images: ['/images/products/oset-125-racing.webp'],
    shortDescription: '12.5-inch starter trials mini-bike for children aged 3-5 with disc brakes and adjustable speed governor.',
    description: 'The OSET 12.5 Racing features real disc brakes front and rear, giving small kids the stopping leverage they need.',
  },
  {
    slug: 'oset-125-eco',
    name: 'OSET 12.5 Eco',
    brand: 'oset',
    brandName: 'OSET',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 2190,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '24V',
      PeakPower: '500W Peak',
      Battery: '8Ah Sealed Lead Acid',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '18 km/h',
      Range: 'Up to 60 minutes',
      Weight: '25 kg',
    },
    images: ['/images/products/oset-125-eco.webp'],
    shortDescription: 'Entry-level 12.5-inch electric starter bike designed to introduce toddlers to two wheels with maximum simplicity.',
    description: 'The OSET 12.5 Eco is an affordable, robust electric bike that teaches young children throttle and brake control.',
  },

  // 10. RFN (APOLLO) (5 models)
  {
    slug: 'rfn-ares-rally-pro',
    name: 'RFN Ares Rally Pro',
    brand: 'rfn-apollo',
    brandName: 'RFN (Apollo)',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 7290,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '74V',
      PeakPower: '12.5 kW Peak',
      Battery: '35Ah (2,590 Wh) LG Cells',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '85 km/h',
      Range: 'Up to 100 km',
      Weight: '68 kg',
    },
    images: ['/images/products/rfn-ares-rally-pro.webp'],
    shortDescription: 'High-tensile steel chromoly framed electric enduro moto with 74V 12.5kW peak power and 4-piston hydraulic brakes.',
    description: 'The RFN Ares Rally Pro by Apollo is built tough for Australian terrain with a full chromoly trellis frame, 74V architecture, and removable battery pack.',
  },
  {
    slug: 'rfn-ares-road-legal-adr',
    name: 'RFN Ares Road Legal (ADR)',
    brand: 'rfn-apollo',
    brandName: 'RFN (Apollo)',
    category: 'adr-road-legal-dirt-bikes',
    subcategoryName: 'ADR Road-Legal Dirt Bikes',
    price: 7890,
    roadLegal: true,
    target: 'Adult',
    badge: 'Road Legal (ADR)',
    featured: true,
    specs: {
      Voltage: '74V',
      PeakPower: '12.5 kW Peak',
      Battery: '35Ah (2,590 Wh)',
      RoadLegal: 'Yes (ADR Compliant)',
      TargetAudience: 'Adult',
      TopSpeed: '85 km/h',
      Range: 'Up to 100 km',
      Weight: '72 kg',
    },
    images: ['/images/products/rfn-ares-road-legal-adr.webp'],
    shortDescription: 'Street-legal ADR-compliant version of the RFN Ares Rally with mirrors, indicators, headlight, and registration readiness.',
    description: 'Fully road registrable across Australian states. The RFN Ares Road Legal offers great versatility as an everyday commuter and weekend bush trail machine.',
  },
  {
    slug: 'rfn-warrior-enduro',
    name: 'RFN Warrior Enduro',
    brand: 'rfn-apollo',
    brandName: 'RFN (Apollo)',
    category: 'full-size-motocross',
    subcategoryName: 'Full-Size Motocross',
    price: 8490,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '74V',
      PeakPower: '12 kW Peak',
      Battery: '43Ah (3,182 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '90 km/h',
      Range: 'Up to 115 km',
      Weight: '75 kg',
    },
    images: ['/images/products/rfn-warrior-enduro.webp'],
    shortDescription: 'Full-size electric enduro with enlarged 43Ah battery, long-travel inverted forks, and 21-inch front off-road wheel.',
    description: 'The RFN Warrior Enduro provides extended outback range and superior rollover clearance on boulders and tree roots.',
  },
  {
    slug: 'apollo-rfn-rxf-e-dirt-junior',
    name: 'Apollo RFN RXF E-Dirt Junior',
    brand: 'rfn-apollo',
    brandName: 'RFN (Apollo)',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 2990,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '48V',
      PeakPower: '1.5 kW Peak',
      Battery: '15Ah (720 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '38 km/h',
      Range: 'Up to 45 km',
      Weight: '36 kg',
    },
    images: ['/images/products/apollo-rfn-rxf-e-dirt-junior.webp'],
    shortDescription: 'Junior electric dirt bike with 48V motor, mechanical disc brakes, and race pit-bike styling for kids aged 7-12.',
    description: 'The Apollo RFN RXF E-Dirt Junior offers true pit-bike styling and solid build quality with zero carburetors to jet.',
  },
  {
    slug: 'apollo-sedna-16-pro-e-balance',
    name: 'Apollo Sedna 16 Pro E-Balance',
    brand: 'rfn-apollo',
    brandName: 'RFN (Apollo)',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 899,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '24V',
      PeakPower: '250W Peak',
      Battery: '5.2Ah Lithium-Ion',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '19 km/h',
      Range: 'Up to 75 minutes',
      Weight: '11 kg',
    },
    images: ['/images/products/apollo-sedna-16-pro-e-balance.webp'],
    shortDescription: '16-inch alloy e-balance bike with rear disc brake and brushless hub motor for groms aged 5-8.',
    description: 'The Apollo Sedna 16 Pro provides the perfect introductory balance experience with reliable brushless motor assist.',
  },

  // 11. ARCTIC LEOPARD (5 models)
  {
    slug: 'arctic-leopard-xe-pro-s',
    name: 'Arctic Leopard XE Pro S',
    brand: 'arctic-leopard',
    brandName: 'Arctic Leopard',
    category: 'full-size-motocross',
    subcategoryName: 'Full-Size Motocross',
    price: 13990,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '80V',
      PeakPower: '20 kW Peak',
      Battery: '50Ah (4,000 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '110 km/h',
      Range: 'Up to 110 km',
      Weight: '79 kg',
    },
    images: ['/images/products/arctic-leopard-xe-pro-s.webp'],
    shortDescription: 'Extreme 80V 20kW peak electric motocross motorcycle with titanium alloy subframe and 580Nm torque.',
    description: 'Engineered for extreme mountain hill climbing and hardcore enduro trails. The Arctic Leopard XE Pro S combines an 80V electrical system with a rigid, lightweight chassis.',
  },
  {
    slug: 'arctic-leopard-xe-800',
    name: 'Arctic Leopard XE 800',
    brand: 'arctic-leopard',
    brandName: 'Arctic Leopard',
    category: 'full-size-motocross',
    subcategoryName: 'Full-Size Motocross',
    price: 12490,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '72V',
      PeakPower: '18 kW Peak',
      Battery: '45Ah (3,240 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '105 km/h',
      Range: 'Up to 100 km',
      Weight: '76 kg',
    },
    images: ['/images/products/arctic-leopard-xe-800.webp'],
    shortDescription: 'Full-size electric enduro machine featuring 18kW peak output, adjustable inverted hydraulic forks, and 21"/18" setup.',
    description: 'The Arctic Leopard XE 800 is a dedicated competition off-road moto offering massive torque and robust suspension performance.',
  },
  {
    slug: 'arctic-leopard-xt-600',
    name: 'Arctic Leopard XT 600',
    brand: 'arctic-leopard',
    brandName: 'Arctic Leopard',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 9990,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '72V',
      PeakPower: '12 kW Peak',
      Battery: '40Ah (2,880 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '90 km/h',
      Range: 'Up to 95 km',
      Weight: '68 kg',
    },
    images: ['/images/products/arctic-leopard-xt-600.webp'],
    shortDescription: 'Agile 72V 12kW electric trail enduro with 40Ah battery pack, forged aluminum frame, and multi-tier regenerative braking.',
    description: 'The XT 600 provides supreme agility through tight forest singletrack and rocky creek beds.',
  },
  {
    slug: 'arctic-leopard-xe-cheetah-youth',
    name: 'Arctic Leopard XE Cheetah Youth',
    brand: 'arctic-leopard',
    brandName: 'Arctic Leopard',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 4490,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '48V',
      PeakPower: '4 kW Peak',
      Battery: '20Ah (960 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '45 km/h',
      Range: 'Up to 50 km',
      Weight: '42 kg',
    },
    images: ['/images/products/arctic-leopard-xe-cheetah-youth.webp'],
    shortDescription: 'Youth electric dirt bike with 4kW motor, hydraulic disc brakes, and progressive throttle for fast-learning teenagers.',
    description: 'The XE Cheetah Youth offers real enduro feel in a reduced scale designed for teenage off-road riders.',
  },
  {
    slug: 'arctic-leopard-xe-road-edition',
    name: 'Arctic Leopard XE Road Edition',
    brand: 'arctic-leopard',
    brandName: 'Arctic Leopard',
    category: 'adr-road-legal-dirt-bikes',
    subcategoryName: 'ADR Road-Legal Dirt Bikes',
    price: 14990,
    roadLegal: true,
    target: 'Adult',
    badge: 'Road Legal (ADR)',
    featured: false,
    specs: {
      Voltage: '80V',
      PeakPower: '20 kW Peak',
      Battery: '50Ah (4,000 Wh)',
      RoadLegal: 'Yes (ADR Compliant)',
      TargetAudience: 'Adult',
      TopSpeed: '110 km/h',
      Range: 'Up to 110 km',
      Weight: '83 kg',
    },
    images: ['/images/products/arctic-leopard-xe-road-edition.webp'],
    shortDescription: 'ADR street-legal 80V 20kW electric dirt bike equipped with full Australian lighting, mirrors, and dual-sport road registration kit.',
    description: 'The XE Road Edition delivers blistering 20kW acceleration on the road and dominates technical off-road tracks on the weekend.',
  },

  // 12. STACYC (5 models)
  {
    slug: 'stacyc-20edrive',
    name: 'STACYC 20eDRIVE',
    brand: 'stacyc',
    brandName: 'STACYC',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 2890,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '36V',
      PeakPower: 'Brushless High-Output Motor',
      Battery: '5Ah 36V PowerPack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '32 km/h',
      Range: 'Up to 60 minutes',
      Weight: '15 kg',
    },
    images: ['/images/products/stacyc-20edrive.webp'],
    shortDescription: '20-inch electric youth dirt bike for kids aged 10-12 with 36V brushless platform and Manitou J-Unit fork.',
    description: 'The STACYC 20eDRIVE is the largest model in the famous eDRIVE family. Features a 36V brushless motor, custom suspension, and disc brakes.',
  },
  {
    slug: 'stacyc-18edrive',
    name: 'STACYC 18eDRIVE',
    brand: 'stacyc',
    brandName: 'STACYC',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 2490,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '36V',
      PeakPower: 'Brushless Platform',
      Battery: '4Ah 36V Lithium Battery',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '29 km/h',
      Range: 'Up to 45 minutes',
      Weight: '14 kg',
    },
    images: ['/images/products/stacyc-18edrive.webp'],
    shortDescription: '18-inch electric balance bike for riders aged 8-10 with brushless 36V power and hydraulic rear brake.',
    description: 'The 18eDRIVE fills the gap for fast-growing groms ready to tackle aggressive pump tracks and dirt jumps.',
  },
  {
    slug: 'stacyc-16edrive-brushless',
    name: 'STACYC 16eDRIVE Brushless',
    brand: 'stacyc',
    brandName: 'STACYC',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 1490,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '20V',
      PeakPower: 'High-Output Brushless Motor',
      Battery: '4Ah Quick-Change Battery',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '21 km/h',
      Range: 'Up to 60 minutes',
      Weight: '9 kg',
    },
    images: ['/images/products/stacyc-16edrive-brushless.webp'],
    shortDescription: '16-inch high-output brushless electric balance bike for kids aged 5-7 with 20% more low-end torque.',
    description: 'The brushless edition of the iconic 16eDRIVE gives groms immediate power out of berms and over dirt rollers.',
  },
  {
    slug: 'stacyc-12edrive',
    name: 'STACYC 12eDRIVE',
    brand: 'stacyc',
    brandName: 'STACYC',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 1050,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '20V',
      PeakPower: '20V Platform',
      Battery: '2Ah Removable Battery',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '14 km/h',
      Range: 'Up to 60 minutes',
      Weight: '7.7 kg',
    },
    images: ['/images/products/stacyc-12edrive.webp'],
    shortDescription: '12-inch starter electric balance bike for toddlers aged 3-5 with 3 progressive power modes.',
    description: 'The original STACYC 12eDRIVE revolutionized how kids learn to ride by replacing training wheels with throttle control.',
  },
  {
    slug: 'stacyc-16edrive-standard',
    name: 'STACYC 16eDRIVE Standard',
    brand: 'stacyc',
    brandName: 'STACYC',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 1190,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '20V',
      PeakPower: '20V Platform',
      Battery: '2Ah Battery Pack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '18 km/h',
      Range: 'Up to 45 minutes',
      Weight: '8.6 kg',
    },
    images: ['/images/products/stacyc-16edrive-standard.webp'],
    shortDescription: '16-inch standard brushed electric balance bike for riders aged 5-7 with aluminium TIG-welded frame.',
    description: 'Reliable and easy to maintain, the standard 16eDRIVE provides hours of backyard fun while teaching core balance skills.',
  },

  // 13. THUMPSTAR (5 models)
  {
    slug: 'thumpstar-z6-72v',
    name: 'Thumpstar Z6 72V',
    brand: 'thumpstar',
    brandName: 'Thumpstar',
    category: 'trail-mid-weight-enduro',
    subcategoryName: 'Trail & Mid-Weight Enduro',
    price: 6499,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '72V',
      PeakPower: '10 kW Peak',
      Battery: '35Ah (2,520 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '85 km/h',
      Range: 'Up to 80 km',
      Weight: '66 kg',
    },
    images: ['/images/products/thumpstar-z6-72v.webp'],
    shortDescription: 'Australian pit-bike heritage meets 72V 10kW electric power with high-tensile frame and heavy-duty suspension.',
    description: 'Thumpstar brings its legendary pit-bike durability to the electric age with the Z6 72V. Instant punch, reinforced swingarm, and plush trail suspension.',
  },
  {
    slug: 'thumpstar-e-pit-1000',
    name: 'Thumpstar E-Pit 1000',
    brand: 'thumpstar',
    brandName: 'Thumpstar',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 2199,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '48V',
      PeakPower: '1 kW Peak',
      Battery: '15Ah (720 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '32 km/h',
      Range: 'Up to 35 km',
      Weight: '38 kg',
    },
    images: ['/images/products/thumpstar-e-pit-1000.webp'],
    shortDescription: 'Junior electric pit-bike featuring 48V 1kW motor, hydraulic disc brakes, and key-switched speed limiter.',
    description: 'The Thumpstar E-Pit 1000 delivers genuine pit-bike thrills for younger riders with clean, quiet, low-maintenance electric drive.',
  },
  {
    slug: 'thumpstar-tse-16',
    name: 'Thumpstar TSE 16',
    brand: 'thumpstar',
    brandName: 'Thumpstar',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 699,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '24V',
      PeakPower: '350W Peak',
      Battery: '5.2Ah Lithium-Ion',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '20 km/h',
      Range: 'Up to 60 minutes',
      Weight: '11 kg',
    },
    images: ['/images/products/thumpstar-tse-16.webp'],
    shortDescription: '16-inch kids electric balance bike with rear disc brake, quick-release battery, and lightweight alloy frame.',
    description: 'An affordable, high-fun balance bike for children aged 5-8 with durable components and Australian warranty support.',
  },
  {
    slug: 'thumpstar-tse-12l',
    name: 'Thumpstar TSE 12L',
    brand: 'thumpstar',
    brandName: 'Thumpstar',
    category: 'balance-mini-bikes',
    subcategoryName: 'Balance & Mini Bikes',
    price: 549,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '18V',
      PeakPower: '250W Peak',
      Battery: '4Ah Lithium Pack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '15 km/h',
      Range: 'Up to 50 minutes',
      Weight: '8.5 kg',
    },
    images: ['/images/products/thumpstar-tse-12l.webp'],
    shortDescription: '12-inch entry-level electric balance bike with low standover height for toddlers aged 3-5.',
    description: 'The Thumpstar TSE 12L introduces toddlers to powered two-wheel balance safely and smoothly.',
  },
  {
    slug: 'thumpstar-z4-electric-offroad',
    name: 'Thumpstar Z4 Electric Offroad',
    brand: 'thumpstar',
    brandName: 'Thumpstar',
    category: 'junior-trials-youth-dirt-bikes',
    subcategoryName: 'Junior Trials & Youth Dirt Bikes',
    price: 3299,
    roadLegal: false,
    target: 'Kids & Youth',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '48V',
      PeakPower: '2.5 kW Peak',
      Battery: '18Ah (864 Wh)',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Kids & Youth',
      TopSpeed: '42 km/h',
      Range: 'Up to 45 km',
      Weight: '45 kg',
    },
    images: ['/images/products/thumpstar-z4-electric-offroad.webp'],
    shortDescription: 'Intermediate youth electric dirt bike featuring 2.5kW brushless motor and inverted front forks.',
    description: 'The Thumpstar Z4 Electric Offroad offers a smooth transition from mini-bikes into full-size dirt riding.',
  },

  // 14. UBCO (5 models)
  {
    slug: 'ubco-2x2-work-bike',
    name: 'UBCO 2X2 Work Bike',
    brand: 'ubco',
    brandName: 'UBCO',
    category: 'utility-farm-e-bikes',
    subcategoryName: 'Utility & Farm E-Bikes',
    price: 7999,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: true,
    specs: {
      Voltage: '52V Dual Motor (AWD)',
      PeakPower: '2.4 kW Peak Dual Hub',
      Battery: '3.1 kWh KXH Powerpack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '50 km/h',
      Range: 'Up to 120 km',
      Weight: '65 kg',
    },
    images: ['/images/products/ubco-2x2-work-bike.webp'],
    shortDescription: 'All-Wheel Drive (2X2) electric utility workhorse with dual hub motors, 3.1kWh battery, and 150kg payload capacity.',
    description: 'Built for tough Australian farm work, cattle mustering, and property maintenance. The UBCO 2X2 Work Bike powers through mud, sand, and steep slopes without scaring livestock or spilling fuel.',
  },
  {
    slug: 'ubco-2x2-adventure-bike',
    name: 'UBCO 2X2 Adventure Bike',
    brand: 'ubco',
    brandName: 'UBCO',
    category: 'utility-farm-e-bikes',
    subcategoryName: 'Utility & Farm E-Bikes',
    price: 8499,
    roadLegal: true,
    target: 'Adult',
    badge: 'Road Legal (ADR)',
    featured: true,
    specs: {
      Voltage: '52V Dual Motor (AWD)',
      PeakPower: '2.4 kW Peak Dual Hub',
      Battery: '3.1 kWh KXH Powerpack',
      RoadLegal: 'Yes (ADR Compliant)',
      TargetAudience: 'Adult',
      TopSpeed: '50 km/h',
      Range: 'Up to 120 km',
      Weight: '70 kg',
    },
    images: ['/images/products/ubco-2x2-adventure-bike.webp'],
    shortDescription: 'ADR road-legal dual-motor AWD utility bike with lights, mirrors, and road registration kit for town and farm duty.',
    description: 'The UBCO 2X2 Adventure Bike is fully road registrable across Australia. Drive on the road to town, carry tools and supplies, and head straight into the paddock with full AWD traction.',
  },
  {
    slug: 'ubco-2x2-hunt-special-edition',
    name: 'UBCO 2X2 Hunt Special Edition',
    brand: 'ubco',
    brandName: 'UBCO',
    category: 'utility-farm-e-bikes',
    subcategoryName: 'Utility & Farm E-Bikes',
    price: 9299,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '52V Dual Motor (AWD)',
      PeakPower: '2.4 kW Peak Dual Hub',
      Battery: '3.1 kWh KXH Powerpack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '50 km/h',
      Range: 'Up to 120 km',
      Weight: '72 kg',
    },
    images: ['/images/products/ubco-2x2-hunt-special-edition.webp'],
    shortDescription: 'Silent stealth AWD utility bike with matte green camouflage livery, gun scabbard mounts, and heavy cargo racks.',
    description: 'Designed for silent wildlife conservation, hunting, and remote station pest management with zero engine sound.',
  },
  {
    slug: 'ubco-2x2-short-wheelbase-compact',
    name: 'UBCO 2X2 Short Wheelbase Compact',
    brand: 'ubco',
    brandName: 'UBCO',
    category: 'utility-farm-e-bikes',
    subcategoryName: 'Utility & Farm E-Bikes',
    price: 6999,
    roadLegal: false,
    target: 'Adult',
    badge: 'Off-Road Only',
    featured: false,
    specs: {
      Voltage: '52V Dual Motor (AWD)',
      PeakPower: '2.0 kW Peak',
      Battery: '2.1 kWh Compact Pack',
      RoadLegal: 'No (Off-Road Only)',
      TargetAudience: 'Adult',
      TopSpeed: '45 km/h',
      Range: 'Up to 80 km',
      Weight: '58 kg',
    },
    images: ['/images/products/ubco-2x2-short-wheelbase-compact.webp'],
    shortDescription: 'Compact short-wheelbase AWD farm bike for tight sheds, horse arenas, and easy transport in utes and trailers.',
    description: 'A lighter, more compact version of UBCO’s dual-motor platform designed for tight spaces and quick paddock hops.',
  },
];
