// src/config/riding-gear.js
// Australian Market Product Catalog: Riding Gear & Protection
// Compliant with Australian Standards (AS/NZS 1698) & ECE 22.06 Road & Motorsport Standards
// Realistic AUD pricing (inc. GST)

export const RIDING_GEAR_CATEGORIES = [
  {
    slug: 'helmets',
    name: 'Full-Face MX & E-Moto Helmets',
    url: '/riding-gear/helmets/',
    description: 'ECE 22.06 and Australian AS/NZS 1698 approved full-face motocross and electric dirt bike helmets engineered with MIPS rotational protection, carbon composite shells, and optimal ventilation.',
    image: 'https://images.unsplash.com/photo-1547038577-da80abbc4f19?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'body-armour',
    name: 'Body Armour & Chest Protectors',
    url: '/riding-gear/body-armour/',
    description: 'CE Level 1 & Level 2 certified hard-shell chest roost deflectors, full upper body protection jackets, carbon composite neck braces, and articulated knee/wrist brace systems.',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'gloves-goggles',
    name: 'Gloves & Off-Road Goggles',
    url: '/riding-gear/gloves-goggles/',
    description: 'Ultra-wide vision motocross goggles with HiPER and Prizm MX lenses, anti-fog Lexan coatings, and high-tensile four-way stretch off-road riding gloves.',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1200&q=80',
  },
  {
    slug: 'boots',
    name: 'Enduro & Motocross Boots',
    url: '/riding-gear/boots/',
    description: 'Heavy-duty hinged motocross and enduro boots with biomechanical ankle pivots, replaceable sole systems (SRS), and deep-lugged traction soles for rugged Australian bush trails.',
    image: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=1200&q=80',
  },
];

export const RIDING_GEAR_SIZES = [
  'Youth S',
  'Youth M',
  'Youth L',
  'Youth XL',
  'Adult XS',
  'Adult S',
  'Adult M',
  'Adult L',
  'Adult XL',
  'Adult 2XL',
];

export const RIDING_GEAR_SAFETY_STANDARDS = [
  'ECE 22.06 Certified',
  'AS/NZS 1698 Approved',
  'CE Level 1',
  'CE Level 2',
];

export const RIDING_GEAR_PRODUCTS = [
  // =========================================================================
  // SUB-CATEGORY 1: Full-Face MX & E-Moto Helmets (ECE 22.06 / AS/NZS 1698 Approved)
  // =========================================================================
  {
    slug: 'fox-racing-v1-matte-black-helmet',
    name: 'Fox Racing V1 Matte Black Helmet',
    price: 299,
    category: 'helmets',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'helmets'],
    brand: 'fox-racing',
    brandName: 'Fox Racing',
    badge: 'ECE 22.06 Certified',
    featured: true,
    isGear: true,
    isHelmet: true,
    safetyStandard: 'ECE 22.06 Certified',
    certifications: ['ECE 22.06', 'AS/NZS 1698 Approved', 'DOT'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult XS', 'Adult S', 'Adult M', 'Adult L', 'Adult XL', 'Adult 2XL'],
    fitmentSize: 'Adult (XS to 2XL)',
    helmetComplianceDisclaimer: 'Complies with Australian Road & Motorsport Standards (ECE 22.06 / AS/NZS 1698)',
    images: ['/images/products/fox-racing-v1-matte-black-helmet.webp'],
    shortDescription: 'ECE 22.06 certified with MIPS multi-directional rotational impact system and lightweight injection-molded polycarbonate shell.',
    description: 'The Fox Racing V1 delivers top-tier safety and comfort for aggressive electric dirt bike riders. Certified to the strict new ECE 22.06 and Australian AS/NZS 1698 standards, it incorporates the MIPS (Multi-Directional Impact Protection System) to reduce rotational forces during angled impacts. Features an advanced intake and exhaust vent system for maximum airflow in harsh Australian summer heat, plus a moisture-wicking removable and washable comfort liner.',
    specs: {
      SafetyCertification: 'ECE 22.06 & Australian AS/NZS 1698 Approved',
      ProtectionSystem: 'MIPS (Multi-Directional Impact Protection System)',
      ShellConstruction: 'Injection-Molded Polycarbonate & ABS Resin',
      Ventilation: '7 Intake Vents & 4 Exhaust Ports for Maximum Airflow',
      VisorSystem: 'Breakaway Visor Screws for Neck Hyperextension Reduction',
      Liner: 'Removable & Washable Moisture-Wicking Antimicrobial Liner',
      Weight: '1,350g (+/- 50g)',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'bell-moto-10-spherical-fasthouse-helmet',
    name: 'Bell Moto-10 Spherical Fasthouse MX Helmet',
    price: 1199,
    category: 'helmets',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'helmets'],
    brand: 'bell',
    brandName: 'Bell Helmets',
    badge: 'Flagship 3K Carbon',
    featured: true,
    isGear: true,
    isHelmet: true,
    safetyStandard: 'ECE 22.06 Certified',
    certifications: ['ECE 22.06', 'AS/NZS 1698 Approved', 'Snell M2020D'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult S', 'Adult M', 'Adult L', 'Adult XL'],
    fitmentSize: 'Adult (S to XL)',
    helmetComplianceDisclaimer: 'Complies with Australian Road & Motorsport Standards (ECE 22.06 / AS/NZS 1698)',
    images: ['/images/products/bell-moto-10-spherical-fasthouse-helmet.webp'],
    shortDescription: 'Spherical MIPS technology, segmented 3K carbon composite shell, and NMR collarbone bumpers for pro competition e-moto.',
    description: 'The pinnacle of off-road helmet engineering. Developed in collaboration with top factory athletes, the Bell Moto-10 Spherical features a segmented 3K carbon fiber shell and Spherical Technology powered by MIPS—a ball-and-socket design that redirects impact energy away from the brain. Equipped with No Missed Races (NMR) EPP collarbone bumpers to prevent clavicle fractures, Magnefusion magnetic emergency-release cheek pads, and Thermal Exchange Airflow System (T.E.A.S.).',
    specs: {
      SafetyCertification: 'Australian AS/NZS 1698, ECE 22.06 & Snell M2020D',
      ProtectionSystem: 'Spherical Technology Powered by MIPS (Ball & Socket Dual Density EPS)',
      ShellConstruction: 'Segmented 3K Carbon Fiber Monocoque',
      CollarboneProtection: 'NMR (No Missed Races) EPP Soft-Compound Bumpers',
      EmergencyRelease: 'Magnefusion Magnetic Emergency Cheek Pad Removal System',
      Ventilation: 'Thermal Exchange Airflow System (T.E.A.S.) with Dual Brow Ports',
      Weight: '1,450g (+/- 50g)',
      Warranty: '5-Year Manufacturer Warranty',
    },
  },
  {
    slug: 'alpinestars-supertech-sm5-compass-helmet',
    name: 'Alpinestars Supertech SM5 Compass Helmet',
    price: 399,
    category: 'helmets',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'helmets'],
    brand: 'alpinestars',
    brandName: 'Alpinestars',
    badge: 'ECE 22.06 / DOT',
    featured: false,
    isGear: true,
    isHelmet: true,
    safetyStandard: 'ECE 22.06 Certified',
    certifications: ['ECE 22.06', 'AS/NZS 1698 Approved', 'DOT'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult XS', 'Adult S', 'Adult M', 'Adult L', 'Adult XL', 'Adult 2XL'],
    fitmentSize: 'Adult (XS to 2XL)',
    helmetComplianceDisclaimer: 'Complies with Australian Road & Motorsport Standards (ECE 22.06 / AS/NZS 1698)',
    images: ['/images/products/alpinestars-supertech-sm5-compass-helmet.webp'],
    shortDescription: 'Thermo-injected polymer shell, engineered patented visor release system, and multiple density EPS collarbone relief.',
    description: 'The Alpinestars Supertech SM5 Compass is engineered through five years of intensive impact research to provide optimal protection and performance. The lightweight thermo-injected polymer shell features varying thickness zones to dissipate energy efficiently. Patented visor release mechanism uncouples regardless of impact angle to minimize rotational torque on the rider’s neck. Specially shaped base profile acts as an energy absorption zone to protect the collarbone.',
    specs: {
      SafetyCertification: 'ECE 22.06, DOT & AS/NZS 1698 Compliant',
      ShellConstruction: 'Advanced High-Impact Thermo-Injected Polymer',
      VisorSystem: 'Patented Visor Release System (Automatic Disengagement at Pre-Set Force)',
      CollarboneRelief: 'Base profile with energy absorption foam protecting the clavicle',
      Ventilation: 'High-Velocity Maximized Air Intake and Multi-Exhaust Channels',
      Liner: 'Silverplus Treated Moisture Wicking & Quick Dry Fabric',
      Weight: '1,370g (+/- 50g)',
      Warranty: '2-Year Australian Warranty',
    },
  },
  {
    slug: 'fox-racing-youth-v1-leed-helmet',
    name: 'Fox Racing Youth V1 Leed Helmet',
    price: 249,
    category: 'helmets',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'helmets'],
    brand: 'fox-racing',
    brandName: 'Fox Racing',
    badge: 'Youth ECE 22.06',
    featured: false,
    isGear: true,
    isHelmet: true,
    safetyStandard: 'ECE 22.06 Certified',
    certifications: ['ECE 22.06', 'AS/NZS 1698 Approved'],
    riderCategory: 'Kids & Youth',
    sizesAvailable: ['Youth S', 'Youth M', 'Youth L'],
    fitmentSize: 'Kids & Youth (Youth S to Youth L)',
    helmetComplianceDisclaimer: 'Complies with Australian Road & Motorsport Standards (ECE 22.06 / AS/NZS 1698)',
    images: ['/images/products/fox-racing-youth-v1-leed-helmet.webp'],
    shortDescription: 'ECE 22.06 approved youth-specific shell with MIPS rotational protection and magnetic visor release system.',
    description: 'Designed specifically for junior e-dirt bike groms, the Fox Racing Youth V1 Leed does not compromise on protection. Sized accurately to young riders’ head proportions with an ultra-lightweight injection-molded shell and integrated MIPS rotational safety technology. Features the MVRS (Magnetic Visor Release System) that safely releases during a crash without snagging on the ground, keeping your child secure.',
    specs: {
      SafetyCertification: 'ECE 22.06 & Australian AS/NZS 1698 Approved',
      TargetAudience: 'Kids, Juniors & Youth Groms (Ages 6 to 15)',
      ProtectionSystem: 'MIPS (Multi-Directional Impact Protection System)',
      VisorSystem: 'MVRS Magnetic Visor Release System',
      Shell: 'Lightweight Injection-Molded ABS & Polycarbonate',
      Liner: 'Removable, Washable Hypoallergenic Youth Comfort Liner',
      Weight: '1,180g (+/- 50g)',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'oneal-3series-crank-youth-mx-helmet',
    name: "O'Neal 3Series Crank Youth MX Helmet",
    price: 189,
    category: 'helmets',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'helmets'],
    brand: 'oneal',
    brandName: "O'Neal",
    badge: 'Youth Entry Pack',
    featured: false,
    isGear: true,
    isHelmet: true,
    safetyStandard: 'ECE 22.06 Certified',
    certifications: ['ECE 22.06', 'AS/NZS 1698 Approved', 'DOT'],
    riderCategory: 'Kids & Youth',
    sizesAvailable: ['Youth S', 'Youth M', 'Youth L', 'Youth XL'],
    fitmentSize: 'Kids & Youth (Youth S to Youth XL)',
    helmetComplianceDisclaimer: 'Complies with Australian Road & Motorsport Standards (ECE 22.06 / AS/NZS 1698)',
    images: ['/images/products/oneal-3series-crank-youth-mx-helmet.webp'],
    shortDescription: 'Ultra-lightweight ABS shell, multi-vent cooling system, and plush removable washable liner for young shredders.',
    description: "The O'Neal 3Series Crank Youth Helmet delivers reliable off-road crash protection for young riders tearing up the track or backyard trails. Built with a durable ABS shell and multi-vent cooling ports to keep junior riders comfortable and focused. Complete with an adjustable height visor, ultra-plush sweat-absorbing liner, and double-D safety chin strap buckle.",
    specs: {
      SafetyCertification: 'ECE 22.06 & AS/NZS 1698 Approved',
      TargetAudience: 'Kids & Youth Riders',
      ShellMaterial: 'High-Impact ABS Composite',
      Ventilation: 'Oversized Chin Bar Air Intakes & Top Extractors',
      Fastening: 'Double-D Safety Ring Buckle with Webbing Retainer',
      Liner: 'Ultra-Plush Sweat Absorbing Padded Liner (Machine Washable)',
      Weight: '1,150g (+/- 50g)',
      Warranty: '1-Year Australian Warranty',
    },
  },

  // =========================================================================
  // SUB-CATEGORY 2: Body Armour & Chest Protectors
  // =========================================================================
  {
    slug: 'leatt-chest-protector-4-5-pro',
    name: 'Leatt Chest Protector 4.5 Pro',
    price: 299,
    category: 'body-armour',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'body-armour'],
    brand: 'leatt',
    brandName: 'Leatt',
    badge: 'CE Level 2 Chest & Back',
    featured: true,
    isGear: true,
    safetyStandard: 'CE Level 2',
    certifications: ['prEN1621-3 Level 2 Chest', 'EN1621-2 Level 2 Back', 'EN1621-1 Flank'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult S', 'Adult M', 'Adult L', 'Adult XL', 'Adult 2XL'],
    fitmentSize: 'Adult Unisex',
    images: ['/images/products/leatt-chest-protector-4-5-pro.webp'],
    shortDescription: 'CE Level 2 certified hard-shell chest and back protector lined with 3DF AirFit impact foam and rib flank guards.',
    description: 'The Leatt 4.5 Pro Chest Protector combines high-density HDPE hard shells with ventilated 3DF AirFit multi-layer impact foam. Certified to CE Level 2 for both chest and back impacts, it provides maximum roost and blunt-force deflection. The multi-plate articulating 3D design ensures uncompromised rider mobility on agile electric dirt bikes, with seamless integration for Leatt neck braces via the BraceOn system.',
    specs: {
      ChestProtection: 'CE Tested and Certified prEN1621-3 Level 2',
      BackProtection: 'CE Tested and Certified EN1621-2 Level 2',
      FlankProtection: 'Padded Multi-Plate Side Rib Guards',
      ImpactFoam: 'Ventilated 3DF AirFit Soft Impact Foam Under Hard Shell',
      NeckBraceIntegration: 'Leatt BraceOn Elastic Neck Brace Fitting System',
      Ventilation: 'Mesh Ventilation Slots for Australian Summer Heat',
      Weight: '1.35 kg',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'alpinestars-bionic-action-v2-protection-jacket',
    name: 'Alpinestars Bionic Action V2 Protection Jacket',
    price: 319,
    category: 'body-armour',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'body-armour'],
    brand: 'alpinestars',
    brandName: 'Alpinestars',
    badge: 'Full Body Guard',
    featured: false,
    isGear: true,
    safetyStandard: 'CE Level 1',
    certifications: ['EN 1621-3:2018 Level 1 Chest', 'EN 1621-2:2014 Level 1 Back', 'EN 1621-1:2012 Level 1 Shoulders/Elbows'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult S', 'Adult M', 'Adult L', 'Adult XL', 'Adult 2XL'],
    fitmentSize: 'Adult (S to 2XL)',
    images: ['/images/products/alpinestars-bionic-action-v2-protection-jacket.webp'],
    shortDescription: 'Full upper body zip jacket with integrated back, chest, shoulder, and elbow guards on breathable stretch mesh.',
    description: 'An ultra-lightweight full-upper protection jacket engineered for off-road enduro and fast trail shredding. Features Cell Technology protectors in the chest and back with an open-cell matrix for exceptional airflow. High-strength polymers on shoulders and elbows offer premium abrasion resistance. The stretch elastane chassis provides a close, unrestrictive anatomical fit under your riding jersey.',
    specs: {
      ChestProtector: 'Nucleon Flex Plus Cell Technology (CE Level 1)',
      BackProtector: 'Ergonomic Contoured Spine Protector (CE Level 1)',
      ShoulderElbow: 'CE Level 1 EN 1621-1 Certified Guards',
      Chassis: 'Breathable Stretch Mesh with Offset Front Central Zipper',
      Adjustability: 'Elastic Kidney Belt with Dual Hook-and-Loop Flaps',
      Weight: '1.25 kg',
      Warranty: '2-Year Australian Warranty',
    },
  },
  {
    slug: 'leatt-gpx-5-5-composite-neck-brace',
    name: 'Leatt GPX 5.5 Composite Neck Brace',
    price: 549,
    category: 'body-armour',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'body-armour'],
    brand: 'leatt',
    brandName: 'Leatt',
    badge: 'Cervical Protection',
    featured: true,
    isGear: true,
    safetyStandard: 'CE Level 2',
    certifications: ['CE Certified as Personal Protective Equipment 89/686/EEC'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult S', 'Adult M', 'Adult L', 'Adult XL'],
    fitmentSize: 'Adult (S/M, L/XL)',
    images: ['/images/products/leatt-gpx-5-5-composite-neck-brace.webp'],
    shortDescription: 'Engineered collarbone cut-out, CoreFlex split rear thoracic strut, and reinforced carbon matrix matrix composite frame.',
    description: 'The Leatt GPX 5.5 is independently lab-tested and proven to reduce serious cervical spine injury risk by up to 89%. Constructed from a rigid carbon-matrix reinforced polyamide matrix that transfers impact force from the fragile neck bones to the larger muscles of the torso. Features an engineered collarbone cut-out to keep your helmet rim away from collarbone bones during crashes.',
    specs: {
      CervicalSpineSafety: 'Reduces critical cervical spine injury by up to 89%',
      FrameConstruction: 'Reinforced Carbon Matrix Composite Resin',
      ThoracicStrut: 'CoreFlex Split Rear Strut Engineered to Snap Before Excessive Pressure on Spine',
      CollarboneCutout: 'Sculpted Clavicle Relief Channel',
      Adjustability: '3-Way SureFit Front and Rear Sliders (No Tools Required)',
      Weight: '790 grams Ultra-Light',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'fox-racing-youth-titan-sport-roost-deflector',
    name: 'Fox Racing Youth Titan Sport Roost Deflector',
    price: 99,
    category: 'body-armour',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'body-armour'],
    brand: 'fox-racing',
    brandName: 'Fox Racing',
    badge: 'Junior Protection',
    featured: false,
    isGear: true,
    safetyStandard: 'CE Level 1',
    certifications: ['CE Level 1 Roost Deflection'],
    riderCategory: 'Kids & Youth',
    sizesAvailable: ['Youth S', 'Youth M', 'Youth L'],
    fitmentSize: 'Kids & Youth (Ages 4-9)',
    images: ['/images/products/fox-racing-youth-titan-sport-roost-deflector.webp'],
    shortDescription: 'Low-profile youth chest and back roost protection with adjustable shoulder straps and side waist buckles.',
    description: 'Give young groms confidence on the dirt with the Fox Youth Titan Sport Roost Deflector. Low-profile hard-shell chest and back plates protect developing torsos from flying stones, roost, and handlebar strikes. Fully adjustable elastic shoulder and waist straps ensure a snug fit that grows with young riders.',
    specs: {
      Coverage: 'Perforated Foam Chassis Contours to Young Rider Body',
      Plates: 'High-Impact Molded Polycarbonate Front and Back Deflectors',
      Fastening: 'Easy-Release Plastic Side Buckles & Adjustable Hook-and-Loop Shoulders',
      TargetRiders: 'Youth & Junior Riders Aged 4 to 9 Years',
      Weight: '480 grams',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'mobius-x8-wrist-knee-brace-system',
    name: 'Mobius X8 Wrist & Knee Brace System',
    price: 899,
    category: 'body-armour',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'body-armour'],
    brand: 'mobius',
    brandName: 'Mobius Braces',
    badge: 'Pro Knee & Wrist System',
    featured: true,
    isGear: true,
    safetyStandard: 'CE Level 2',
    certifications: ['CE Medical Device Grade Level 2', 'EN 1621-1'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult S', 'Adult M', 'Adult L', 'Adult XL'],
    fitmentSize: 'Adult (S to XL)',
    images: ['/images/products/mobius-x8-wrist-knee-brace-system.webp'],
    shortDescription: 'Continuous Cable Routing System (CCRS), hyperextension prevention, and rigid glass-reinforced nylon shell.',
    description: 'Trusted by Ryan Villopoto and Ken Roczen, the Mobius X8 is the benchmark in off-road orthopedic joint protection. Utilizes the patented Continuous Cable Routing System (CCRS) that progressively resists hyperextension, hyperflexion, and rotational twists during violent crashes on high-torque electric dirt bikes.',
    specs: {
      ProtectionMechanism: 'Patented CCRS (Continuous Cable Routing System) Dynamic Tensioning',
      Shell: 'Glass-Reinforced Nylon Outer Shell with Forged Aluminum Extension Stops',
      HyperextensionLimits: 'Adjustable Extension Stop Dial from 0 to 30 Degrees',
      Liner: 'Plush EVA Foam Cushioning with Quick-Release Numbered Straps',
      MedicalCertification: 'Registered Orthopedic Grade Knee & Joint Stabilizer',
      Weight: '880 grams per brace',
      Warranty: '1-Year Australian Warranty',
    },
  },

  // =========================================================================
  // SUB-CATEGORY 3: Gloves & Off-Road Goggles
  // =========================================================================
  {
    slug: '100-percent-armega-goggles-hiper-mirror-lens',
    name: '100% Armega Goggles with HiPER Mirror Lens',
    price: 189,
    category: 'gloves-goggles',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'gloves-goggles'],
    brand: '100-percent',
    brandName: '100%',
    badge: 'HiPER Ultra HD',
    featured: true,
    isGear: true,
    safetyStandard: 'CE Level 1',
    certifications: ['ANSI Z87.1', 'EN 1938 Off-Road Goggle Standard'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult S', 'Adult M', 'Adult L', 'Adult XL'],
    fitmentSize: 'Universal Adult',
    images: ['/images/products/100-percent-armega-goggles-hiper-mirror-lens.webp'],
    shortDescription: 'Ultra HD optical clarity, 6-point locking tabs, force air intake ports, and triple-layer perforated face foam.',
    description: 'The 100% Armega offers unmatched visual clarity on the trails with category-defining Ultra HD optical lens technology. Features the contrast-enhancing HiPER mirror lens that sharpens trail contours and ruts in changing light conditions. Dual-injection frame with 6-point locking tabs lets you swap lenses in seconds, while integrated force-air intake ports circulate cooling air to eliminate fogging.',
    specs: {
      LensTechnology: 'HiPER Contrast-Enhancing Injection-Molded Shatterproof Ultra HD Lens',
      LensRetention: '6-Point Locking System with Dual Quick-Release Latches',
      SweatManagement: 'Next-Gen Perforated Triple-Layer Moisture Wicking Face Foam',
      Strap: 'Ultra-Wide 48mm Silicone-Coated Non-Slip Strap',
      NoseGuard: 'Removable Roost Nose Guard Included',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'oakley-airbrake-mx-factory-pilot-goggles',
    name: 'Oakley Airbrake MX Factory Pilot Goggles',
    price: 249,
    category: 'gloves-goggles',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'gloves-goggles'],
    brand: 'oakley',
    brandName: 'Oakley',
    badge: 'Prizm MX Lens',
    featured: true,
    isGear: true,
    safetyStandard: 'CE Level 1',
    certifications: ['ANSI Z87.1', 'EN 1938'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult S', 'Adult M', 'Adult L', 'Adult XL'],
    fitmentSize: 'Universal Adult',
    images: ['/images/products/oakley-airbrake-mx-factory-pilot-goggles.webp'],
    shortDescription: 'Prizm MX lens, Switchlock quick lens-change system, and high-impact Plutonite pre-curved lens.',
    description: 'The Oakley Airbrake MX is the first off-road goggle with a high-impact Plutonite pre-curved lens for true optical perfection. Featuring Prizm MX lens tuning that highlights subtle transitions in dirt, sand, and clay so you can pick the fastest lines. Oakley Switchlock Technology makes lens changing fast and effortless when trail conditions change.',
    specs: {
      LensMaterial: 'Injection-Molded Plutonite (100% UVA / UVB / UVC Protection)',
      Optics: 'Prizm MX Lens for Maximum Color Contrast on Aussie Tracks',
      LensLock: 'Switchlock Dual Mechanical Locking Levers',
      Frame: 'Exoskeleton Outer Chassis with Flexible O Matter Faceplate',
      Strap: 'Adjustable 50mm Strap with Triple Silicone Ribbing',
      Warranty: '2-Year Oakley Warranty',
    },
  },
  {
    slug: '100-percent-strata-2-youth-off-road-goggles',
    name: '100% Strata 2 Youth Off-Road Goggles',
    price: 45,
    category: 'gloves-goggles',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'gloves-goggles'],
    brand: '100-percent',
    brandName: '100%',
    badge: 'Youth Clear Vision',
    featured: false,
    isGear: true,
    safetyStandard: 'CE Level 1',
    certifications: ['EN 1938 Youth Certified'],
    riderCategory: 'Kids & Youth',
    sizesAvailable: ['Youth S', 'Youth M', 'Youth L'],
    fitmentSize: 'Kids & Youth',
    images: ['/images/products/100-percent-strata-2-youth-off-road-goggles.webp'],
    shortDescription: 'Anti-fog coated Lexan lens, 40mm silicone-coated strap, and curved youth face fitment.',
    description: 'Tailored specifically for junior helmets and smaller faces, the 100% Strata 2 Youth delivers exceptional field of vision and dust sealing for young e-moto riders. The anti-fog coated polycarbonate lens keeps vision crystal clear through dust clouds, while the plush dual-layer face foam manages sweat comfortably.',
    specs: {
      Lens: 'Anti-Fog, Scratch-Resistant Lexan Polycarbonate Lens',
      FieldOfView: '17.5% Larger Vertical Field of View than Gen 1',
      Strap: '40mm Wide Silicone-Coated Non-Slip Strap for Youth Helmets',
      Foam: 'Dual-Layer Ultra-Soft Face Foam for Snug Dust Seal',
      TearOffPosts: 'Integrated Dual-Post Tear-Off Mounts',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'fox-racing-airline-motocross-gloves',
    name: 'Fox Racing Airline Motocross Gloves',
    price: 49,
    category: 'gloves-goggles',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'gloves-goggles'],
    brand: 'fox-racing',
    brandName: 'Fox Racing',
    badge: 'Ultra-Breathable',
    featured: false,
    isGear: true,
    safetyStandard: 'CE Level 1',
    certifications: ['CE Level 1 Off-Road'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult S', 'Adult M', 'Adult L', 'Adult XL', 'Adult 2XL'],
    fitmentSize: 'Adult (S to 2XL)',
    images: ['/images/products/fox-racing-airline-motocross-gloves.webp'],
    shortDescription: 'Single-layer Clarino palm, neoprene slip-on cuff, and ultra-breathable stretch nylon for summer riding.',
    description: 'The Fox Airline Glove is built for riders seeking maximum feel on electric dirt bike throttles and brake levers. Minimalist slip-on neoprene cuff design eliminates wrist pressure points, while the perforated single-layer Clarino palm delivers exceptional handlebar feedback with zero bunching.',
    specs: {
      Palm: 'Perforated Single-Layer Clarino Synthetic Suede',
      TopHand: 'Ultra-Light 4-Way Stretch Nylon for Maximum Airflow',
      Cuff: 'Slip-On Embossed Neoprene Cuff (Hook-and-Loop Free)',
      Fingers: 'Silicone Gripper Print on Lever Fingers & Stretch Mesh Gussets',
      Touchscreen: 'Conductive Clarino Touchscreen Finger Compatible',
      Warranty: '1-Year Australian Warranty',
    },
  },

  // =========================================================================
  // SUB-CATEGORY 4: Enduro & Motocross Boots
  // =========================================================================
  {
    slug: 'alpinestars-tech-7-enduro-boots',
    name: 'Alpinestars Tech 7 Enduro Boots',
    price: 599,
    category: 'boots',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'boots'],
    brand: 'alpinestars',
    brandName: 'Alpinestars',
    badge: 'Trail Lugged Sole',
    featured: true,
    isGear: true,
    safetyStandard: 'CE Level 2',
    certifications: ['CE Certified EN 13634:2017 Level 2'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult XS', 'Adult S', 'Adult M', 'Adult L', 'Adult XL', 'Adult 2XL'],
    fitmentSize: 'Adult (US 7 to US 14)',
    images: ['/images/products/alpinestars-tech-7-enduro-boots.webp'],
    shortDescription: 'Specially engineered compound sole with deep lugs for trail grip, dual biomechanical hinge, and TPU shin plate.',
    description: 'The Alpinestars Tech 7 Enduro Boot features a purpose-engineered vulcanized dual-compound sole with aggressive lugs for superior grip when pushing your electric dirt bike through mud, steep creek crossings, and rocky outcrops. The biomechanical ankle pivot system delivers progressive flexion control while shielding the joint from torsional twisting.',
    specs: {
      SafetyCertification: 'CE Certified to EN 13634:2017 (Level 2 Protection)',
      SoleType: 'Enduro-Specific High-Traction Lugged Dual-Compound Sole',
      AnkleSystem: 'Dual Biomechanical Blade Pivot with Medial and Lateral Reinforcement',
      Buckles: '4 Aluminum Memory Buckles with Self-Aligning Quick Release',
      Gaiter: 'Extended Microfiber Gaiter Prevents Water and Dirt Ingress',
      Weight: '1.95 kg per boot',
      Warranty: '2-Year Australian Warranty',
    },
  },
  {
    slug: 'sidi-crossfire-3-srs-boots',
    name: 'Sidi Crossfire 3 SRS Boots',
    price: 799,
    category: 'boots',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'boots'],
    brand: 'sidi',
    brandName: 'Sidi',
    badge: 'SRS Replaceable Sole',
    featured: true,
    isGear: true,
    safetyStandard: 'CE Level 2',
    certifications: ['CE Certified EN 13634 Level 2'],
    riderCategory: 'Adult',
    sizesAvailable: ['Adult S', 'Adult M', 'Adult L', 'Adult XL', 'Adult 2XL'],
    fitmentSize: 'Adult (Euro 41 to 48)',
    images: ['/images/products/sidi-crossfire-3-srs-boots.webp'],
    shortDescription: 'Sole Replacement System (SRS), Dual Flex ankle pivot, adjustable calf system, and hyperextension block.',
    description: 'Handcrafted in Italy, the Sidi Crossfire 3 SRS is the ultimate off-road competition boot. Featuring the patented SRS (Sole Replacement System) allowing riders to switch between MX and Enduro soles with standard screws. Dual Flex ankle pivot with a mechanical hyperextension block prevents ankle over-rotation during violent foot-dabs on fast singletrack.',
    specs: {
      SafetyCertification: 'CE Approved EN 13634 Level 2',
      SoleSystem: 'SRS Dovetail Sole (Replaceable in minutes with screwdriver)',
      AnklePivot: 'Dual Flex System with Mechanical Hyperextension Block',
      CalfPlate: 'Adjustable Calf System to Accommodate Large Knee Braces',
      Buckles: 'Cam-Lock Micro-Adjustable Replaceable Buckle Straps',
      Origin: 'Made in Italy',
      Warranty: '2-Year Australian Warranty',
    },
  },
  {
    slug: 'fox-racing-comp-youth-boots',
    name: 'Fox Racing Comp Youth Boots',
    price: 229,
    category: 'boots',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'boots'],
    brand: 'fox-racing',
    brandName: 'Fox Racing',
    badge: 'Youth MX Boot',
    featured: false,
    isGear: true,
    safetyStandard: 'CE Level 1',
    certifications: ['CE Certified EN 13634'],
    riderCategory: 'Kids & Youth',
    sizesAvailable: ['Youth S', 'Youth M', 'Youth L'],
    fitmentSize: 'Kids & Youth (Youth 1 to Youth 7)',
    images: ['/images/products/fox-racing-comp-youth-boots.webp'],
    shortDescription: 'Internal lace system, TPU shin plate and toe cap, and durable high-density rubber outsole for junior riders.',
    description: 'Engineered with the same DNA as Fox adult pro boots, scaled down for young groms. Features an internal speed-lace system that locks the foot in place, full TPU shin, toe cap, and calf protection against hard peg impacts, and durable high-density rubber soles for confident grip.',
    specs: {
      SafetyCertification: 'CE Certified Youth Off-Road Boot',
      TargetAudience: 'Kids & Youth Groms (Shoe sizes Youth 1 to 7)',
      Lacing: 'Internal Speed Lace System with Easy Pull Loop',
      ArmorPlates: 'Injection-Molded TPU Shin, Ankle & Burn Guards',
      Buckles: 'ActiveLock Silicone Lower Strap with Two Sturdy Positive-Lock Buckles',
      Weight: '1.15 kg per boot',
      Warranty: '1-Year Australian Warranty',
    },
  },
  {
    slug: 'alpinestars-tech-3s-youth-motocross-boots',
    name: 'Alpinestars Tech 3S Youth Motocross Boots',
    price: 249,
    category: 'boots',
    parentCategory: 'riding-gear',
    parentCategories: ['riding-gear', 'boots'],
    brand: 'alpinestars',
    brandName: 'Alpinestars',
    badge: 'Junior Track Spec',
    featured: false,
    isGear: true,
    safetyStandard: 'CE Level 1',
    certifications: ['CE Certified EN 13634:2010'],
    riderCategory: 'Kids & Youth',
    sizesAvailable: ['Youth S', 'Youth M', 'Youth L'],
    fitmentSize: 'Kids & Youth (US 10 to US 13)',
    images: ['/images/products/alpinestars-tech-3s-youth-motocross-boots.webp'],
    shortDescription: 'Designed specifically for junior riders with 3 memory buckles, flex zones, and replaceable anatomical footbed.',
    description: 'Designed specifically for small junior riders taking their first laps on STACYC, OSET, or KTM SX-E 5 electric bikes. The Alpinestars Tech 3S features low-height construction for easier gear shifting and foot controls, flexible accordion zones for comfort, and a three-buckle memory closure system for quick entry.',
    specs: {
      SafetyCertification: 'CE Certified to EN 13634:2010',
      TargetAudience: 'Junior & Mini E-Moto Riders',
      Construction: 'Reinforced Microfiber Upper with Molded TPU Shin Protection',
      BuckleSystem: '3 Polymer Memory Buckles with Self-Aligning Ratchet',
      Footbed: 'Removable Anatomical Footbed (Accommodates Growth Inserts)',
      Weight: '980 grams per boot',
      Warranty: '2-Year Australian Warranty',
    },
  },
];
